# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see https://www.gnu.org/licenses/.

- name: Add Grafana repository key
  ansible.builtin.apt_key:
    url: https://packages.grafana.com/gpg.key
    id: 4E40DDF6D76E284A4A6780E48C8C34C524098CB6
    state: present
  become: yes

- name: Add Grafana repository
  apt_repository:
    repo: deb https://packages.grafana.com/oss/deb beta main
    state: present
  become: yes

- name: Install packages
  apt:
    update_cache: yes
    pkg:
      - grafana
    state: latest
  become: yes

- name: Prepare Grafana base directories
  file:
    path: '{{ item }}'
    state: directory
    owner: root
    group: root
    mode: '0755'
  loop:
    - '{{ grafana_root_path }}'
    - '{{ grafana_root_path }}/provision'
    - '{{ grafana_root_path }}/provision/access-control'
    - '{{ grafana_root_path }}/provision/dashboards'
    - '{{ grafana_root_path }}/provision/datasources'
    - '{{ grafana_root_path }}/provision/notifiers'
    - '{{ grafana_root_path }}/provision/plugins'
    - '{{ grafana_root_path }}/dashboards'
  become: yes

- name: Prepare Grafana data directory
  file:
    path: '{{ grafana_root_path }}/data'
    state: directory
    owner: grafana
    group: grafana
    mode: '0700'
  become: yes

- name: Configure Grafana
  template:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    mode: '0644'
  register: nginx_config
  loop:
    - src: 'grafana.ini.j2'
      dest: '{{ grafana_root_path }}/grafana.ini'
    - src: 'grafana_dashboards.yml.j2'
      dest: '{{ grafana_root_path }}/provision/dashboards/ansible.yml'
    - src: 'grafana_datasources.yml.j2'
      dest: '{{ grafana_root_path }}/provision/datasources/ansible.yml'
  become: yes

- name: Configure Grafana dashboards
  copy:
    src: '{{ item }}'
    dest: '{{ grafana_root_path }}/dashboards/{{ item | basename }}'
    mode: '0644'
  loop: '{{ lookup("fileglob", "dashboards/*.json", wantlist = True) }}'
  become: yes

- name: Link Grafana configuration
  file:
    path: /etc/grafana/grafana.ini
    state: link
    src: '{{ grafana_root_path }}/grafana.ini'
    force: yes
    follow: no
  become: yes

- name: Restart Grafana services
  service:
    name: grafana-server
    state: restarted
    enabled: yes
  when: 'not ansible_check_mode'
  become: yes
