# ------------ Mandatory settings ------------

[General]
# Your instance title
Title =
# Public-facing URL
URL =

[S3]
# Endpoint and bucket, example: https://sos-de-fra-1.exo.io/bucket
Location =
# AWS/S3 access key ID
AccessKeyID = 
# AWS/S3 secret access key
SecretKey =

[SMTP]
# SMTP information
# Read the CURL documentation for supported URLs: https://everything.curl.dev/usingcurl/smtp.html
URL = 
Username =
Password =
From =

# ------------ Optional settings ------------

# [Data]
# RootDirectory = .
# DatabaseFile = redropp.db
# TempDirectory = tmp

# [HTTP]
# Port = 8894

# [Drop]
# Quota = 1G
# MaxDuration = 90d
# AllowInfinite = No
