{
 "title": "Overview",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "Node",
    "label": "Hosts:",
    "query": {
     "query": "label_values(node_uname_info, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Goupile", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "systemd_unit_start_time_seconds { name=~\"goupile@.*\" } == 0",
     "legendFormat": "{{ name }}"
    },
    {
     "expr": "time() - systemd_unit_start_time_seconds { name=~\"goupile@.*\" } < time()",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(systemd_process_cpu_seconds_total{ name=~\"goupile@.*\" }[$__rate_interval])",
     "legendFormat": "{{ name }}"
    },
    {
     "expr": "count without(cpu, mode) (node_cpu_seconds_total{mode=\"idle\",instance=\"host1\"})",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Resident memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "systemd_process_resident_memory_bytes { name=~\"goupile@.*\" }",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  { "title": "Hosts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up { job = \"node_exporter\" }",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  { "title": "Host: $Node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 }, "repeat": "Node" },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode=\"system\",instance=\"$Node\"}[$__rate_interval]))",
     "legendFormat": "Busy System"
    },
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode=\"user\",instance=\"$Node\"}[$__rate_interval]))",
     "legendFormat": "Busy User"
    },
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode=\"iowait\",instance=\"$Node\"}[$__rate_interval]))",
     "legendFormat": "Busy Iowait"
    },
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode=~\".*irq\",instance=\"$Node\"}[$__rate_interval]))",
     "legendFormat": "Busy IRQs"
    },
    {
     "expr": "sum (rate(node_cpu_seconds_total{mode!=\"idle\",mode!=\"user\",mode!=\"system\",mode!=\"iowait\",mode!=\"irq\",mode!=\"softirq\",instance=\"$Node\"}[$__rate_interval]))",
     "legendFormat": "Busy Other"
    },
    {
     "expr": "count without(cpu, mode) (node_cpu_seconds_total{mode=\"idle\",instance=\"$Node\"})",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 16 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$Node\"}",
     "legendFormat": "RAM Total"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$Node\"} - node_memory_MemFree_bytes{instance=\"$Node\"} - (node_memory_Cached_bytes{instance=\"$Node\"} + node_memory_Buffers_bytes{instance=\"$Node\"})",
     "legendFormat": "RAM Used"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=\"$Node\"} + node_memory_Buffers_bytes{instance=\"$Node\"}",
     "legendFormat": "RAM Cache + Buffer"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=\"$Node\"}",
     "legendFormat": "RAM Free"
    },
    {
     "expr": "(node_memory_SwapTotal_bytes{instance=\"$Node\"} - node_memory_SwapFree_bytes{instance=\"$Node\"})",
     "legendFormat": "SWAP Used"
    }
   ]
  },
  {
   "title": "Network",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{instance=\"$Node\"}[$__rate_interval])*8",
     "legendFormat": "recv {{device}}"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{instance=\"$Node\"}[$__rate_interval])*8",
     "legendFormat": "trans {{device}} "
    }
   ]
  },
  {
   "title": "Disk",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 16 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{instance=\"$Node\",device!~\"rootfs\"} * 100) / node_filesystem_size_bytes{instance=\"$Node\",device!~\"rootfs\"})",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  }
 ]
}