# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see https://www.gnu.org/licenses/.

proxy_ip = '192.168.33.10'
server_ip = '192.168.33.11'

Vagrant.configure('2') do |config|
    config.vm.box = 'generic/debian10'

    config.hostmanager.enabled = true
    config.hostmanager.manage_host = true

    config.vm.define 'proxy' do |proxy|
        proxy.vm.box = 'generic/debian10'
        proxy.vm.hostname = 'proxy.local'
        proxy.vm.network 'private_network', ip: proxy_ip

        proxy.vm.provider 'virtualbox' do |v|
            v.name = 'vagrant_proxy'
            v.memory = 2048
            v.cpus = 2
            v.linked_clone = true
            v.gui = false
        end
    end

    config.vm.define 'server' do |server|
        server.vm.hostname = 'server.local'
        server.vm.network 'private_network', ip: server_ip

        server.vm.provider 'virtualbox' do |v|
            v.name = 'vagrant_server'
            v.memory = 2048
            v.cpus = 2
            v.linked_clone = true
            v.gui = false
        end

        server.vm.provision 'ansible' do |ansible|
            ansible.playbook = '../../hds.yml'
            ansible.limit = 'all'
            ansible.inventory_path = '../../inventories/hds/vagrant.yml'
            ansible.extra_vars = { ansible_python_interpreter: '/usr/bin/python3' }
            # ansible.raw_arguments = ['--check']
        end
    end
end
