# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see https://www.gnu.org/licenses/.

distrib = 'generic/debian11'
proxy_ip = '192.168.57.2'
server_ip = '192.168.57.3'

Vagrant.configure('2') do |config|
    config.hostmanager.enabled = true
    config.hostmanager.manage_host = true

    config.vm.define 'server_node' do |m|
        m.vm.box = distrib
        m.vm.hostname = 'hds-server.local'
        m.vm.network 'private_network', ip: server_ip

        m.vm.provider 'virtualbox' do |v|
            v.name = 'hds_server'
            v.memory = 2048
            v.cpus = 2
            v.linked_clone = true
            v.gui = false
        end
    end

    config.vm.define 'proxy_node' do |m|
        m.vm.box = distrib
        m.vm.hostname = 'hds.local'
        m.vm.network 'private_network', ip: proxy_ip

        # It's kind of ugly to hardcode this but.. meh. Keep it simple
        m.hostmanager.aliases = ['goupile1.hds.local', 'goupile2.hds.local']

        m.vm.provider 'virtualbox' do |v|
            v.name = 'hds_proxy'
            v.memory = 2048
            v.cpus = 2
            v.linked_clone = true
            v.gui = false
        end

        m.vm.provision 'ansible' do |ansible|
            ansible.playbook = '../../hds.yml'
            ansible.limit = 'all'
            ansible.inventory_path = '../../inventories/hds/vagrant/hosts.yml'
            ansible.extra_vars = { ansible_python_interpreter: '/usr/bin/python3' }
            # ansible.raw_arguments = ['--check']
        end
    end
end
