#!/usr/bin/env python3

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.

import sys
import re
import argparse

def parse_properties_xid(f):
    id_start = []
    id_continue = []

    version = next(f).strip("\n\r \t#") + ' -- ' + next(f).strip("\n\r \t#")

    for line in f:
        line = line.strip()

        if not line or line[0] == '#':
            continue

        parts = [part.strip() for part in re.split('[;#]', line)]
        if len(parts) < 3:
            continue

        if '..' in parts[0]:
            start, end = parts[0].split('..')
        else:
            start, end = parts[0], parts[0]
        start, end = int(start, 16), int(end, 16)

        if parts[1] == 'ID_Start':
            id_start.append((start, end + 1))
        elif parts[1] == 'ID_Continue':
            id_continue.append((start, end + 1))

    return (version, id_start, id_continue)

def write_xid_header(version, id_start, id_continue, f):
    f.write(f"""// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program. If not, see <https://www.gnu.org/licenses/>.

// This file is autogenerated by lexer_xid_gen.py
// Version: {version}

namespace RG {{

static const int32_t bk_UnicodeIdStartTable[] = {{""")
    for i, v in enumerate(id_start):
        if i % 5 == 0: f.write('\n   ')
        f.write(f' 0x{v[0]:05X}, 0x{v[1]:05X}{"," if i + 1 < len(id_start) else ""}')
    f.write("""
};

static const int32_t bk_UnicodeIdContinueTable[] = {""")
    for i, v in enumerate(id_continue):
        if i % 5 == 0: f.write('\n   ')
        f.write(f' 0x{v[0]:05X}, 0x{v[1]:05X}{"," if i + 1 < len(id_continue) else ""}')
    f.write("""
};

}
""")

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description = 'Create lexer_xid.hh (blikk) from Unicode file DerivedCoreProperties.txt')
    parser.add_argument('filename', metavar = 'source', type = str, nargs = 1,
                        help = 'path to DerivedCoreProperties.txt')
    args = parser.parse_args()

    with open(args.filename[0], 'r') as f:
        version, id_start, id_continue = parse_properties_xid(f)

    write_xid_header(version, id_start, id_continue, sys.stdout)
