# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see https://www.gnu.org/licenses/.

nginx_public_addr: '{{ ansible_host }}'

nginx_domains:
  - name: '{{ prometheus_public_addr }}'
    config: |
      ssl_client_certificate /opt/nginx/ssl/internal/ca.crt;
      ssl_verify_client on;
      ssl_verify_depth 2;

      {% for exporter in prometheus_exporters %}

      location /metrics/{{ exporter }} {
          allow {{ hostvars.monitor.nginx_public_addr }};
          deny all;

          proxy_set_header Host $host;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

          proxy_pass http://127.0.0.1:{{ prometheus_packages[exporter].port }}/metrics;
      }
      {% endfor %}

  - name: goupile.fr
    ssl_certbot_email: niels.martignene@protonmail.com
    config: |
      location = /en {
          return 301 https://$host/en/;
      }
      location / {
          index index.html;

          rewrite ^/en/$ /en/index.html;
          rewrite ^(/?(?:en/)?[a-zA-Z0-9]+)$ $1.html;
          rewrite ^(/?(?:en/)?[a-zA-Z0-9]+)/$ $1 permanent;
          try_files $uri $uri/ =404;

          root /opt/static/live/goupile.fr/www;

          location /demo/ {
              error_page 404 /demo/index.html;
          }
      }

      location /files/ {
          alias /opt/static/live/goupile.fr/files/;

          location ~ ^/files/[a-zA-Z0-9_]+/ {
              autoindex on;
              autoindex_exact_size off;
          }
      }

      location /pknet {
          limit_req zone=default burst=100 nodelay;

          proxy_set_header Host $host;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

          proxy_pass http://127.0.0.1:9200;
      }
  - name: www.goupile.fr
    ssl_certbot_email: niels.martignene@protonmail.com
    config: |
      location / {
          return 301 https://goupile.fr$request_uri;
      }

  - name: goupile.org
    ssl_certbot_email: niels.martignene@protonmail.com
    config: |
      location / {
          return 301 https://goupile.fr$request_uri;
      }
  - name: www.goupile.org
    ssl_certbot_email: niels.martignene@protonmail.com
    config: |
      location / {
          return 301 https://goupile.fr$request_uri;
      }

  - name: koromix.dev
    ssl_certbot_email: niels.martignene@protonmail.com
    config: |
      location / {
          index index.html;

          rewrite ^/en/$ /en/index.html;
          rewrite ^(/?(?:en/)?[a-zA-Z0-9]+)$ $1.html;
          rewrite ^(/?(?:en/)?[a-zA-Z0-9]+)/$ $1 permanent;
          try_files $uri $uri/ =404;

          root /opt/static/live/koromix.dev/www;
      }

      location /files/ {
          alias /opt/static/live/koromix.dev/files/;

          location ~ ^/files/[a-zA-Z0-9_]+/ {
              autoindex on;
              autoindex_exact_size off;
          }
      }
      location /test/ {
          alias /opt/static/live/koromix.dev/test/;
      }

      # Some stuff still lives on the old server
      location /R/ {
          proxy_pass http://192.168.196.250;
      }
      location /procemot/ {
          client_max_body_size 256M;
          proxy_pass http://192.168.196.250;
      }
  - name: www.koromix.dev
    ssl_certbot_email: niels.martignene@protonmail.com
    config: |
      location / {
          return 301 https://koromix.dev$request_uri;
      }

  - name: groupile.fr
    ssl_certbot_email: niels.martignene@protonmail.com
    config: |
      location / {
          return 302 https://goupile.fr$request_uri;
      }

  - name: koffi.dev
    ssl_certbot_email: niels.martignene@protonmail.com
    config: |
      location / {
          index index.html;

          rewrite ^/en/$ /en/index.html;
          rewrite ^(/?(?:en/)?[a-zA-Z0-9]+)$ $1.html;
          rewrite ^(/?(?:en/)?[a-zA-Z0-9]+)/$ $1 permanent;
          try_files $uri $uri/ =404;

          root /opt/static/live/koffi.dev/www;

          expires 1h;
          add_header Cache-Control "public, no-transform";

          gzip on;
          gzip_vary on;
          gzip_types text/plain text/css text/xml text/javascript application/x-javascript application/xml;
          gzip_proxied no-cache no-store private expired auth;
          gzip_min_length 1000;

          location /_static/ {
              expires 1d;
          }
      }

  - name: carto.cn2r.fr
    ssl_certbot_email: niels.martignene@protonmail.com
    config: |
      location / {
          proxy_pass http://127.0.0.1:9977/cn2r/;
      }

      # Some stuff still lives on the old server
      location /R/ {
          proxy_pass http://192.168.196.250;
      }

  - name: carto.demheter.fr
    ssl_certbot_email: niels.martignene@protonmail.com
    config: |
      location / {
          proxy_pass http://127.0.0.1:9977/demheter/;
      }

  - name: carto.koromix.dev
    ssl_certbot_email: niels.martignene@protonmail.com
    config: |
      location / {
          proxy_pass http://127.0.0.1:9977/;
      }
