# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see https://www.gnu.org/licenses/.

static_deploys:
  - name: goupile.fr/www
    repo: https://github.com/Koromix/rygel.git
    path: web/goupile.fr
  - name: goupile.fr/files

  - name: koromix.dev/www
    repo: https://github.com/Koromix/rygel.git
    path: web/koromix.dev/dist
    build:
      - cmd: '{{ static_root_path }}/repo/koromix.dev/www/bootstrap.sh'
        chdir: '{{ static_root_path }}/repo/koromix.dev/www'
      - cmd: '/usr/bin/rm -rf {{ static_root_path }}/repo/koromix.dev/www/web/koromix.dev/dist'
        chdir: '{{ static_root_path }}/repo/koromix.dev/www'
      - cmd: '{{ static_root_path }}/repo/koromix.dev/www/felix -pFast --run_here hodler . -O dist'
        chdir: '{{ static_root_path }}/repo/koromix.dev/www/web/koromix.dev'
  - name: koromix.dev/files
  - name: koromix.dev/test

  - name: koffi.dev/www
    repo: https://github.com/Koromix/rygel.git
    version: master
    path: web/koffi.dev/dist/html
    build:
      - cmd: '/root/.local/share/pypoetry/venv/bin/poetry install'
        chdir: '{{ static_root_path }}/repo/koffi.dev/www/web/koffi.dev'
      - cmd: '/root/.local/share/pypoetry/venv/bin/poetry run make clean'
        chdir: '{{ static_root_path }}/repo/koffi.dev/www/web/koffi.dev'
      - cmd: '/root/.local/share/pypoetry/venv/bin/poetry run make html'
        chdir: '{{ static_root_path }}/repo/koffi.dev/www/web/koffi.dev'

  - name: demheter.fr/beta
    repo: https://github.com/Koromix/rygel.git
    path: web/demheter.fr/dist
    build:
      - cmd: '{{ static_root_path }}/repo/demheter.fr/beta/bootstrap.sh'
        chdir: '{{ static_root_path }}/repo/demheter.fr/beta'
      - cmd: '/usr/bin/rm -rf {{ static_root_path }}/repo/demheter.fr/beta/web/demheter.fr/dist'
        chdir: '{{ static_root_path }}/repo/demheter.fr/beta'
      - cmd: '{{ static_root_path }}/repo/demheter.fr/beta/felix -pFast --run_here hodler . -O dist'
        chdir: '{{ static_root_path }}/repo/demheter.fr/beta/web/demheter.fr'
