# ------------ Mandatory settings ------------

[General]
# Your instance title
Title =
# Public-facing URL
URL =

[SMTP]
# SMTP information
# Read the CURL documentation for supported URLs: https://everything.curl.dev/usingcurl/smtp.html
URL = 
Username =
Password =
From =

# ------------ Optional settings ------------

# [Authentication]
# AllowInternal = Yes
# AllowRegister = Yes

# [Data]
# RootDirectory = .
# DatabaseFile = redropp.db
# TempDirectory = tmp

# [HTTP]
# Port = 8893
