# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see https://www.gnu.org/licenses/.

ansible_host: 152.228.219.68
ansible_port: 22
ansible_user: ansible
ansible_ssh_private_key_file: ~/.ssh/pknet/prod
ansible_python_interpreter: /usr/bin/python3

ovh_ipv6_addr: 2001:41d0:304:200::24ca
ovh_ipv6_netmask: 128
ovh_ipv6_gateway: 2001:41d0:304:200::1
