// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/.

let bridge = (function() {
    function translateInt(value)
    {
        value = parseInt(value);
        return isNaN(value) ? null : value;
    }

    function translateFloat(value)
    {
        value = parseFloat(value);
        return isNaN(value) ? null : value;
    }

    function translateSimpleEnum(value)
    {
        if (value === 'autre') {
            return 999;
        } else {
            return translateInt(value);
        }
    }

    function translateMultiEnum(value)
    {
        if (value !== null && value !== undefined && value !== '') {
            return value.split('|').map(x => translateSimpleEnum(x));
        } else {
            return [];
        }
    }

    // FIXME: Fix handling of dictionaries (broken detection of 'autre' values)
    function translateRow(row)
    {
        let row2 = {
            neuropsy_evaluateur: row['neuropsy.evaluateur'] || null,
            neuropsy_plainte_cog: translateSimpleEnum(row['neuropsy.plainte_cog']),
            neuropsy_plainte_cog_inquietude: translateSimpleEnum(row['neuropsy.plainte_cog_inquietude']),
            neuropsy_plainte_cog_details: row['neuropsy.plainte_cog_details'] || null,
            neuropsy_plainte_thym: translateSimpleEnum(row['neuropsy.plainte_thym']),
            neuropsy_plainte_thym_details: row['neuropsy.plainte_thym_details'] || null,
            neuropsy_plainte_anx: translateSimpleEnum(row['neuropsy.plainte_anx']),
            neuropsy_plainte_anx_details: row['neuropsy.plainte_anx_details'] || null,
            neuropsy_plainte_som: translateSimpleEnum(row['neuropsy.plainte_som']),
            neuropsy_plainte_som_details: row['neuropsy.plainte_som_details'] || null,
            neuropsy_quali_coop: translateSimpleEnum(row['neuropsy.quali_coop']),
            neuropsy_quali_comptmt: translateSimpleEnum(row['neuropsy.quali_comptmt']),
            neuropsy_quali_attention: translateSimpleEnum(row['neuropsy.quali_attention']),
            neuropsy_quali_langage: translateSimpleEnum(row['neuropsy.quali_langage']),
            neuropsy_quali_comprehension: translateSimpleEnum(row['neuropsy.quali_comprehension']),
            neuropsy_frein_oui_non: translateSimpleEnum(row['neuropsy.frein_oui_non']),
            neuropsy_freins: translateMultiEnum(row['neuropsy.freins']),
            neuropsy_quali_comm: row['neuropsy.quali_comm'] || null,
            neuropsy_nsc: translateSimpleEnum(row['neuropsy.nsc']),
            neuropsy_npsy_adapt_geria12: translateSimpleEnum(row['neuropsy.npsy_adapt_geria12']),
            neuropsy_npsy_adapt_victoria: translateSimpleEnum(row['neuropsy.npsy_adapt_victoria']),
            neuropsy_npsy_adapt_pasat: translateSimpleEnum(row['neuropsy.npsy_adapt_pasat']),
            neuropsy_score_moca: translateFloat(row['neuropsy.score_moca']),
            neuropsy_moca_c50: translateSimpleEnum(row['neuropsy.moca_c50']),
            neuropsy_moca_c5: translateSimpleEnum(row['neuropsy.moca_c5']),
            neuropsy_score_moca_z: translateFloat(row['neuropsy.score_moca_z']),
            neuropsy_moca_interp: translateSimpleEnum(row['neuropsy.moca_interp']),
            neuropsy_moca_comm: row['neuropsy.moca_comm'] || null,
            neuropsy_score_rimm1: translateInt(row['neuropsy.score_rimm1']),
            neuropsy_score_rimm2: translateInt(row['neuropsy.score_rimm2']),
            neuropsy_score_rimm_interp: translateSimpleEnum(row['neuropsy.score_rimm_interp']),
            neuropsy_score_3rl: translateInt(row['neuropsy.score_3rl']),
            neuropsy_score_2rl: translateInt(row['neuropsy.score_2rl']),
            neuropsy_rl_c50: translateSimpleEnum(row['neuropsy.rl_c50']),
            neuropsy_rl_c5: translateSimpleEnum(row['neuropsy.rl_c5']),
            neuropsy_score_3rl_z: translateFloat(row['neuropsy.score_3rl_z']),
            neuropsy_score_2rl_z: translateFloat(row['neuropsy.score_2rl_z']),
            neuropsy_score_3rl_interp: translateSimpleEnum(row['neuropsy.score_3rl_interp']),
            neuropsy_score_3rt: translateInt(row['neuropsy.score_3rt']),
            neuropsy_score_2rt: translateInt(row['neuropsy.score_2rt']),
            neuropsy_rt_c50: translateSimpleEnum(row['neuropsy.rt_c50']),
            neuropsy_rt_c5: translateSimpleEnum(row['neuropsy.rt_c5']),
            neuropsy_score_3rt_z: translateFloat(row['neuropsy.score_3rt_z']),
            neuropsy_score_2rt_z: translateFloat(row['neuropsy.score_2rt_z']),
            neuropsy_score_3rt_interp: translateSimpleEnum(row['neuropsy.score_3rt_interp']),
            neuropsy_score_rt3: translateInt(row['neuropsy.score_rt3']),
            neuropsy_score_rt2: translateInt(row['neuropsy.score_rt2']),
            neuropsy_score_rtdiff: translateInt(row['neuropsy.score_rtdiff']),
            neuropsy_score_rt3_interp: translateSimpleEnum(row['neuropsy.score_rt3_interp']),
            neuropsy_episod_comm: row['neuropsy.episod_comm'] || null,
            neuropsy_score_tmta_temps: translateInt(row['neuropsy.score_tmta_temps']),
            neuropsy_score_tmta_erreurs: translateInt(row['neuropsy.score_tmta_erreurs']),
            neuropsy_tmta_c50: translateSimpleEnum(row['neuropsy.tmta_c50']),
            neuropsy_tmta_c5: translateSimpleEnum(row['neuropsy.tmta_c5']),
            neuropsy_score_tmta_z: translateFloat(row['neuropsy.score_tmta_z']),
            neuropsy_score_tmta_interp: translateSimpleEnum(row['neuropsy.score_tmta_interp']),
            neuropsy_tmta_comm: row['neuropsy.tmta_comm'] || null,
            neuropsy_score_deno_temps: translateInt(row['neuropsy.score_deno_temps']),
            neuropsy_score_deno_erreurs: translateInt(row['neuropsy.score_deno_erreurs']),
            neuropsy_deno_c50: translateSimpleEnum(row['neuropsy.deno_c50']),
            neuropsy_deno_c5: translateSimpleEnum(row['neuropsy.deno_c5']),
            neuropsy_score_deno_z: translateFloat(row['neuropsy.score_deno_z']),
            neuropsy_score_deno_interp: translateSimpleEnum(row['neuropsy.score_deno_interp']),
            neuropsy_deno_comm: row['neuropsy.deno_comm'] || null,
            neuropsy_score_lecture_temps: translateInt(row['neuropsy.score_lecture_temps']),
            neuropsy_score_lecture_erreurs: translateInt(row['neuropsy.score_lecture_erreurs']),
            neuropsy_lecture_c50: translateSimpleEnum(row['neuropsy.lecture_c50']),
            neuropsy_lecture_c5: translateSimpleEnum(row['neuropsy.lecture_c5']),
            neuropsy_score_lecture_z: translateFloat(row['neuropsy.score_lecture_z']),
            neuropsy_score_lecture_interp: translateSimpleEnum(row['neuropsy.score_lecture_interp']),
            neuropsy_lecture_comm: row['neuropsy.lecture_comm'] || null,
            neuropsy_score_code_corrects: translateInt(row['neuropsy.score_code_corrects']),
            neuropsy_score_code_erreurs1: translateInt(row['neuropsy.score_code_erreurs1']),
            neuropsy_score_code_erreurs2: translateInt(row['neuropsy.score_code_erreurs2']),
            neuropsy_score_code_omissions: translateInt(row['neuropsy.score_code_omissions']),
            neuropsy_code_std: translateInt(row['neuropsy.code_std']),
            neuropsy_code_c50: translateSimpleEnum(row['neuropsy.code_c50']),
            neuropsy_code_c5: translateSimpleEnum(row['neuropsy.code_c5']),
            neuropsy_score_code_z: translateFloat(row['neuropsy.score_code_z']),
            neuropsy_score_code_interp: translateSimpleEnum(row['neuropsy.score_code_interp']),
            neuropsy_code_comm: row['neuropsy.code_comm'] || null,
            neuropsy_score_tmtb_temps: translateInt(row['neuropsy.score_tmtb_temps']),
            neuropsy_score_tmtb_erreurs: translateInt(row['neuropsy.score_tmtb_erreurs']),
            neuropsy_tmtb_c50: translateSimpleEnum(row['neuropsy.tmtb_c50']),
            neuropsy_tmtb_c5: translateSimpleEnum(row['neuropsy.tmtb_c5']),
            neuropsy_score_tmtb_z: translateFloat(row['neuropsy.score_tmtb_z']),
            neuropsy_score_tmtb_interp: translateSimpleEnum(row['neuropsy.score_tmtb_interp']),
            neuropsy_tmtb_comm: row['neuropsy.tmtb_comm'] || null,
            neuropsy_score_interf_temps1: translateInt(row['neuropsy.score_interf_temps1']),
            neuropsy_score_interf_temps2: translateInt(row['neuropsy.score_interf_temps2']),
            neuropsy_score_interf_erreurs1: translateInt(row['neuropsy.score_interf_erreurs1']),
            neuropsy_score_interf_erreurs2: translateInt(row['neuropsy.score_interf_erreurs2']),
            neuropsy_interf_c50: translateSimpleEnum(row['neuropsy.interf_c50']),
            neuropsy_interf_c5: translateSimpleEnum(row['neuropsy.interf_c5']),
            neuropsy_score_interf_z: translateFloat(row['neuropsy.score_interf_z']),
            neuropsy_score_interf_interp: translateSimpleEnum(row['neuropsy.score_interf_interp']),
            neuropsy_interf_comm: row['neuropsy.interf_comm'] || null,
            neuropsy_seqlc_score_brut: translateInt(row['neuropsy.seqlc_score_brut']),
            neuropsy_seqlc_std: translateInt(row['neuropsy.seqlc_std']),
            neuropsy_seqlc_c50: translateSimpleEnum(row['neuropsy.seqlc_c50']),
            neuropsy_seqlc_c5: translateSimpleEnum(row['neuropsy.seqlc_c5']),
            neuropsy_seqlc_score_z: translateFloat(row['neuropsy.seqlc_score_z']),
            neuropsy_seqlc_interp: translateSimpleEnum(row['neuropsy.seqlc_interp']),
            neuropsy_seqlc_comm: row['neuropsy.seqlc_comm'] || null,
            neuropsy_pasat_score_brut: translateInt(row['neuropsy.pasat_score_brut']),
            neuropsy_pasat_score_cent: translateInt(row['neuropsy.pasat_score_cent']),
            neuropsy_pasat_score_z: translateFloat(row['neuropsy.pasat_score_z']),
            neuropsy_pasat_erreurs_telescop: translateInt(row['neuropsy.pasat_erreurs_telescop']),
            neuropsy_pasat_erreurs_non_reponses: translateInt(row['neuropsy.pasat_erreurs_non_reponses']),
            neuropsy_pasat_erreurs_calcul: translateInt(row['neuropsy.pasat_erreurs_calcul']),
            neuropsy_pasat_non_reponses: translateInt(row['neuropsy.pasat_non_reponses']),
            neuropsy_pasat_interp: translateSimpleEnum(row['neuropsy.pasat_interp']),
            neuropsy_pasat_comm: row['neuropsy.pasat_comm'] || null,
            neuropsy_score_flu1_correct: translateInt(row['neuropsy.score_flu1_correct']),
            neuropsy_score_flu1_erreurs: translateInt(row['neuropsy.score_flu1_erreurs']),
            neuropsy_score_flu1_repet: translateInt(row['neuropsy.score_flu1_repet']),
            neuropsy_flu1_c50: translateSimpleEnum(row['neuropsy.flu1_c50']),
            neuropsy_flu1_c5: translateSimpleEnum(row['neuropsy.flu1_c5']),
            neuropsy_score_flu1_z: translateFloat(row['neuropsy.score_flu1_z']),
            neuropsy_score_flu1_interp: translateSimpleEnum(row['neuropsy.score_flu1_interp']),
            neuropsy_flu1_comm: row['neuropsy.flu1_comm'] || null,
            neuropsy_score_flu2_correct: translateInt(row['neuropsy.score_flu2_correct']),
            neuropsy_score_flu2_erreurs: translateInt(row['neuropsy.score_flu2_erreurs']),
            neuropsy_score_flu2_repet: translateInt(row['neuropsy.score_flu2_repet']),
            neuropsy_flu2_c50: translateSimpleEnum(row['neuropsy.flu2_c50']),
            neuropsy_flu2_c5: translateSimpleEnum(row['neuropsy.flu2_c5']),
            neuropsy_score_flu2_z: translateFloat(row['neuropsy.score_flu2_z']),
            neuropsy_score_flu2_interp: translateSimpleEnum(row['neuropsy.score_flu2_interp']),
            neuropsy_flu2_comm: row['neuropsy.flu2_comm'] || null,
            neuropsy_synthese: row['neuropsy.synthese'] || null,
            neuropsy_objectifs: row['neuropsy.objectifs'] || null,
            neuropsy_proposition_coaching: translateSimpleEnum(row['neuropsy.proposition_coaching']),
            neuropsy_forme_coaching: translateSimpleEnum(row['neuropsy.forme_coaching']),
            aq1_prev1: translateSimpleEnum(row['aq1.prev1']),
            aq1_prev2: translateSimpleEnum(row['aq1.prev2']),
            aq1_prev3: translateSimpleEnum(row['aq1.prev3']),
            aq1_prev4: translateSimpleEnum(row['aq1.prev4']),
            aq1_prev5: translateSimpleEnum(row['aq1.prev5']),
            aq1_prev6: translateSimpleEnum(row['aq1.prev6']),
            aq1_prev7: translateSimpleEnum(row['aq1.prev7']),
            aq1_prev8: translateSimpleEnum(row['aq1.prev8']),
            aq1_prev9: translateSimpleEnum(row['aq1.prev9']),
            aq1_prev10: translateSimpleEnum(row['aq1.prev10']),
            aq1_alim1: translateSimpleEnum(row['aq1.alim1']),
            aq1_alim2: translateSimpleEnum(row['aq1.alim2']),
            aq1_alim3: translateSimpleEnum(row['aq1.alim3']),
            aq1_alim4: translateSimpleEnum(row['aq1.alim4']),
            aq1_alim5: translateSimpleEnum(row['aq1.alim5']),
            aq1_alim6: translateSimpleEnum(row['aq1.alim6']),
            aq1_alim7: translateSimpleEnum(row['aq1.alim7']),
            aq1_alim8: translateSimpleEnum(row['aq1.alim8']),
            aq1_alim9: translateSimpleEnum(row['aq1.alim9']),
            aq1_alim10: translateSimpleEnum(row['aq1.alim10']),
            aq1_alim11: translateSimpleEnum(row['aq1.alim11']),
            aq1_alim12: translateSimpleEnum(row['aq1.alim12']),
            aq1_alim13: translateSimpleEnum(row['aq1.alim13']),
            aq1_alim14: translateSimpleEnum(row['aq1.alim14']),
            aq1_alim15: translateSimpleEnum(row['aq1.alim15']),
            aq1_activ1: translateSimpleEnum(row['aq1.activ1']),
            aq1_activ2: translateSimpleEnum(row['aq1.activ2']),
            aq1_activ3: translateSimpleEnum(row['aq1.activ3']),
            aq1_activ4: translateSimpleEnum(row['aq1.activ4']),
            aq1_alcool1: translateSimpleEnum(row['aq1.alcool1']),
            aq1_alcool2: translateSimpleEnum(row['aq1.alcool2']),
            aq1_alcool3c: translateInt(row['aq1.alcool3c']),
            aq1_alcool3b: translateInt(row['aq1.alcool3b']),
            aq1_alcool3a: translateInt(row['aq1.alcool3a']),
            aq1_alcool4: translateSimpleEnum(row['aq1.alcool4']),
            aq1_alcool5: translateSimpleEnum(row['aq1.alcool5']),
            aq1_alcool6: translateSimpleEnum(row['aq1.alcool6']),
            aq1_alcool7: translateSimpleEnum(row['aq1.alcool7']),
            aq1_alcool8: translateSimpleEnum(row['aq1.alcool8']),
            aq1_alcool9: translateSimpleEnum(row['aq1.alcool9']),
            aq1_alcool10: translateSimpleEnum(row['aq1.alcool10']),
            aq1_alcool11: translateSimpleEnum(row['aq1.alcool11']),
            aq1_alcool12: translateSimpleEnum(row['aq1.alcool12']),
            aq1_alcool13: translateSimpleEnum(row['aq1.alcool13']),
            aq1_tabac1: translateSimpleEnum(row['aq1.tabac1']),
            aq1_tabac2: translateSimpleEnum(row['aq1.tabac2']),
            aq1_tabac3: translateSimpleEnum(row['aq1.tabac3']),
            aq1_tabac4: translateSimpleEnum(row['aq1.tabac4']),
            aq1_tabac5: translateSimpleEnum(row['aq1.tabac5']),
            aq1_tabac6: translateInt(row['aq1.tabac6']),
            aq1_tabac7: translateSimpleEnum(row['aq1.tabac7']),
            aq1_tabac8: translateSimpleEnum(row['aq1.tabac8']),
            aq1_tabac9: translateSimpleEnum(row['aq1.tabac9']),
            aq1_drog1: translateSimpleEnum(row['aq1.drog1']),
            aq1_risq1: translateSimpleEnum(row['aq1.risq1']),
            aq1_risq2: translateSimpleEnum(row['aq1.risq2']),
            aq1_risq3: translateSimpleEnum(row['aq1.risq3']),
            aq1_som1: translateMultiEnum(row['aq1.som1']),
            aq1_som2: translateSimpleEnum(row['aq1.som2']),
            aq1_som3: translateMultiEnum(row['aq1.som3']),
            aq1_som4: translateSimpleEnum(row['aq1.som4']),
            aq1_som5: translateSimpleEnum(row['aq1.som5']),
            aq1_strav1: translateSimpleEnum(row['aq1.strav1']),
            aq1_strav2: translateSimpleEnum(row['aq1.strav2']),
            aq1_strav3: translateSimpleEnum(row['aq1.strav3']),
            aq1_strav4: translateSimpleEnum(row['aq1.strav4']),
            aq1_strav5: translateSimpleEnum(row['aq1.strav5']),
            aq1_strav6: translateSimpleEnum(row['aq1.strav6']),
            aq1_strav7: translateSimpleEnum(row['aq1.strav7']),
            aq1_eq5d1: translateSimpleEnum(row['aq1.eq5d1']),
            aq1_eq5d2: translateSimpleEnum(row['aq1.eq5d2']),
            aq1_eq5d3: translateSimpleEnum(row['aq1.eq5d3']),
            aq1_eq5d4: translateSimpleEnum(row['aq1.eq5d4']),
            aq1_eq5d5: translateSimpleEnum(row['aq1.eq5d5']),
            aq1_eq5d6: translateInt(row['aq1.eq5d6']),
            aq1_had1: translateSimpleEnum(row['aq1.had1']),
            aq1_had2: translateSimpleEnum(row['aq1.had2']),
            aq1_had3: translateSimpleEnum(row['aq1.had3']),
            aq1_had4: translateSimpleEnum(row['aq1.had4']),
            aq1_had5: translateSimpleEnum(row['aq1.had5']),
            aq1_had6: translateSimpleEnum(row['aq1.had6']),
            aq1_had7: translateSimpleEnum(row['aq1.had7']),
            aq1_had8: translateSimpleEnum(row['aq1.had8']),
            aq1_had9: translateSimpleEnum(row['aq1.had9']),
            aq1_had10: translateSimpleEnum(row['aq1.had10']),
            aq1_had11: translateSimpleEnum(row['aq1.had11']),
            aq1_had12: translateSimpleEnum(row['aq1.had12']),
            aq1_had13: translateSimpleEnum(row['aq1.had13']),
            aq1_had14: translateSimpleEnum(row['aq1.had14']),
            aq1_had15: translateSimpleEnum(row['aq1.had15']),
            aq1_cra: translateSimpleEnum(row['aq1.cra']),
            aq1_cra1: translateSimpleEnum(row['aq1.cra1']),
            aq1_cra2: translateMultiEnum(row['aq1.cra2']),
            aq1_sitfam1: translateSimpleEnum(row['aq1.sitfam1']),
            aq1_sitfam2: translateSimpleEnum(row['aq1.sitfam2']),
            aq1_integsoc1: translateSimpleEnum(row['aq1.integsoc1']),
            aq1_integsoc2: translateSimpleEnum(row['aq1.integsoc2']),
            aq1_integsoc3: translateSimpleEnum(row['aq1.integsoc3']),
            aq1_integsoc4: translateSimpleEnum(row['aq1.integsoc4']),
            aq1_integsoc5: translateSimpleEnum(row['aq1.integsoc5']),
            aq1_integsoc6: translateSimpleEnum(row['aq1.integsoc6']),
            aq1_integsoc7: translateSimpleEnum(row['aq1.integsoc7']),
            aq1_integsoc8: translateSimpleEnum(row['aq1.integsoc8']),
            aq1_trav1: translateSimpleEnum(row['aq1.trav1']),
            aq1_trav2: translateSimpleEnum(row['aq1.trav2']),
            aq1_trav3: translateSimpleEnum(row['aq1.trav3']),
            aq1_trav4: row['aq1.trav4'] || null,
            aq1_evtvie1: translateSimpleEnum(row['aq1.evtvie1']),
            aq1_evtvie2: row['aq1.evtvie2'] || null,
            aq1_evtvie3: translateSimpleEnum(row['aq1.evtvie3']),
            aq1_evtvie4: translateSimpleEnum(row['aq1.evtvie4']),
            aq1_evtvie5: translateSimpleEnum(row['aq1.evtvie5']),
            aq1_evtvie6: translateSimpleEnum(row['aq1.evtvie6']),
            aq1_evtvie7: translateSimpleEnum(row['aq1.evtvie7']),
            aq1_evtvie8: translateSimpleEnum(row['aq1.evtvie8']),
            aq1_lois1: translateMultiEnum(row['aq1.lois1']),
            aq1_lois2: translateSimpleEnum(row['aq1.lois2']),
            aq1_lois3: translateSimpleEnum(row['aq1.lois3']),
            aq1_lois4: translateSimpleEnum(row['aq1.lois4']),
            aq1_retr1: translateInt(row['aq1.retr1']),
            aq1_retr2: translateSimpleEnum(row['aq1.retr2']),
            aq1_retr3: translateSimpleEnum(row['aq1.retr3']),
            aq1_retr4: translateSimpleEnum(row['aq1.retr4']),
            aq1_retr5: translateSimpleEnum(row['aq1.retr5']),
            aq1_retr6: translateMultiEnum(row['aq1.retr6']),
            aq1_seco1: translateSimpleEnum(row['aq1.seco1']),
            aq1_seco2: translateSimpleEnum(row['aq1.seco2']),
            aq1_seco3: translateSimpleEnum(row['aq1.seco3']),
            aq1_seco4: translateSimpleEnum(row['aq1.seco4']),
            aq1_seco5: translateSimpleEnum(row['aq1.seco5']),
            aq1_seco6: translateMultiEnum(row['aq1.seco6']),
            aq1_seco7: translateSimpleEnum(row['aq1.seco7']),
            aq1_seco8: translateSimpleEnum(row['aq1.seco8']),
            aq1_seco9: translateSimpleEnum(row['aq1.seco9']),
            aq2_chgmt1: translateSimpleEnum(row['aq2.chgmt1']),
            aq2_chgmt2: translateMultiEnum(row['aq2.chgmt2']),
            aq2_chgmt3: row['aq2.chgmt3'] || null,
            aq2_sgen1: translateSimpleEnum(row['aq2.sgen1']),
            aq2_sgen2: translateSimpleEnum(row['aq2.sgen2']),
            aq2_sgen3: translateSimpleEnum(row['aq2.sgen3']),
            aq2_sgen4: translateSimpleEnum(row['aq2.sgen4']),
            aq2_cardioa1: translateSimpleEnum(row['aq2.cardioa1']),
            aq2_cardioa2: translateInt(row['aq2.cardioa2']),
            aq2_cardiob1: translateSimpleEnum(row['aq2.cardiob1']),
            aq2_cardiob2: translateInt(row['aq2.cardiob2']),
            aq2_cardioc1: translateSimpleEnum(row['aq2.cardioc1']),
            aq2_cardioc2: translateInt(row['aq2.cardioc2']),
            aq2_cardiod1: translateSimpleEnum(row['aq2.cardiod1']),
            aq2_cardiod2: translateInt(row['aq2.cardiod2']),
            aq2_cardioe1: translateSimpleEnum(row['aq2.cardioe1']),
            aq2_cardioe2: translateInt(row['aq2.cardioe2']),
            aq2_cardiof1: translateSimpleEnum(row['aq2.cardiof1']),
            aq2_cardiof2: translateInt(row['aq2.cardiof2']),
            aq2_cardiog1: translateSimpleEnum(row['aq2.cardiog1']),
            aq2_cardiog2: translateInt(row['aq2.cardiog2']),
            aq2_cardioh1: translateSimpleEnum(row['aq2.cardioh1']),
            aq2_cardioh2: translateInt(row['aq2.cardioh2']),
            aq2_cardioi1: translateSimpleEnum(row['aq2.cardioi1']),
            aq2_cardioi2: translateInt(row['aq2.cardioi2']),
            aq2_cardioj1: translateSimpleEnum(row['aq2.cardioj1']),
            aq2_cardioj2: translateInt(row['aq2.cardioj2']),
            aq2_respia1: translateSimpleEnum(row['aq2.respia1']),
            aq2_respia2: translateInt(row['aq2.respia2']),
            aq2_respib1: translateSimpleEnum(row['aq2.respib1']),
            aq2_respib2: translateInt(row['aq2.respib2']),
            aq2_digesta1: translateSimpleEnum(row['aq2.digesta1']),
            aq2_digesta2: translateInt(row['aq2.digesta2']),
            aq2_digestb1: translateSimpleEnum(row['aq2.digestb1']),
            aq2_digestb2: translateInt(row['aq2.digestb2']),
            aq2_digestc1: translateSimpleEnum(row['aq2.digestc1']),
            aq2_digestc2: translateInt(row['aq2.digestc2']),
            aq2_digestd1: translateSimpleEnum(row['aq2.digestd1']),
            aq2_digestd2: translateInt(row['aq2.digestd2']),
            aq2_digeste1: translateSimpleEnum(row['aq2.digeste1']),
            aq2_digeste2: translateInt(row['aq2.digeste2']),
            aq2_uroa1: translateSimpleEnum(row['aq2.uroa1']),
            aq2_uroa2: translateInt(row['aq2.uroa2']),
            aq2_urob1: translateSimpleEnum(row['aq2.urob1']),
            aq2_urob2: translateInt(row['aq2.urob2']),
            aq2_uroc1: translateSimpleEnum(row['aq2.uroc1']),
            aq2_uroc2: translateInt(row['aq2.uroc2']),
            aq2_gynec1: translateInt(row['aq2.gynec1']),
            aq2_gynec2: translateSimpleEnum(row['aq2.gynec2']),
            aq2_gynec3: translateSimpleEnum(row['aq2.gynec3']),
            aq2_gynec4: translateSimpleEnum(row['aq2.gynec4']),
            aq2_gynec5: translateSimpleEnum(row['aq2.gynec5']),
            aq2_neuroa1: translateSimpleEnum(row['aq2.neuroa1']),
            aq2_neuroa2: translateInt(row['aq2.neuroa2']),
            aq2_neurob1: translateSimpleEnum(row['aq2.neurob1']),
            aq2_neurob2: translateInt(row['aq2.neurob2']),
            aq2_osteoa1: translateSimpleEnum(row['aq2.osteoa1']),
            aq2_osteoa2: translateInt(row['aq2.osteoa2']),
            aq2_osteob1: translateSimpleEnum(row['aq2.osteob1']),
            aq2_osteob2: translateInt(row['aq2.osteob2']),
            aq2_osteoc1: translateSimpleEnum(row['aq2.osteoc1']),
            aq2_osteoc2: translateInt(row['aq2.osteoc2']),
            aq2_osteod1: translateSimpleEnum(row['aq2.osteod1']),
            aq2_osteod2: translateInt(row['aq2.osteod2']),
            aq2_osteoe1: translateSimpleEnum(row['aq2.osteoe1']),
            aq2_osteoe2: translateInt(row['aq2.osteoe2']),
            aq2_endoa1: translateSimpleEnum(row['aq2.endoa1']),
            aq2_endoa2: translateInt(row['aq2.endoa2']),
            aq2_endob1: translateSimpleEnum(row['aq2.endob1']),
            aq2_endob2: translateInt(row['aq2.endob2']),
            aq2_cancer1: translateSimpleEnum(row['aq2.cancer1']),
            aq2_cancera1: translateSimpleEnum(row['aq2.cancera1']),
            aq2_cancera2: translateInt(row['aq2.cancera2']),
            aq2_cancerb1: translateSimpleEnum(row['aq2.cancerb1']),
            aq2_cancerb2: translateInt(row['aq2.cancerb2']),
            aq2_cancerc1: translateSimpleEnum(row['aq2.cancerc1']),
            aq2_cancerc2: translateInt(row['aq2.cancerc2']),
            aq2_cancerd1: translateSimpleEnum(row['aq2.cancerd1']),
            aq2_cancerd2: translateInt(row['aq2.cancerd2']),
            aq2_cancere1: translateSimpleEnum(row['aq2.cancere1']),
            aq2_cancere2: translateInt(row['aq2.cancere2']),
            aq2_cancerf1: translateSimpleEnum(row['aq2.cancerf1']),
            aq2_cancerf2: translateInt(row['aq2.cancerf2']),
            aq2_cancerg1: translateSimpleEnum(row['aq2.cancerg1']),
            aq2_cancerg2: translateInt(row['aq2.cancerg2']),
            aq2_cancerh1: translateSimpleEnum(row['aq2.cancerh1']),
            aq2_cancerh2: translateInt(row['aq2.cancerh2']),
            aq2_canceri1: translateSimpleEnum(row['aq2.canceri1']),
            aq2_canceri2: translateInt(row['aq2.canceri2']),
            aq2_cancerj1: translateSimpleEnum(row['aq2.cancerj1']),
            aq2_cancerj2: translateInt(row['aq2.cancerj2']),
            aq2_cancerk1: translateSimpleEnum(row['aq2.cancerk1']),
            aq2_cancerk2: translateInt(row['aq2.cancerk2']),
            aq2_cancerl1: translateSimpleEnum(row['aq2.cancerl1']),
            aq2_cancerl2: translateInt(row['aq2.cancerl2']),
            aq2_cancerm1: translateSimpleEnum(row['aq2.cancerm1']),
            aq2_cancerm2: translateInt(row['aq2.cancerm2']),
            aq2_sensoa1: translateSimpleEnum(row['aq2.sensoa1']),
            aq2_sensoa2: translateInt(row['aq2.sensoa2']),
            aq2_sensob1: translateSimpleEnum(row['aq2.sensob1']),
            aq2_sensob2: translateInt(row['aq2.sensob2']),
            aq2_sensoc1: translateSimpleEnum(row['aq2.sensoc1']),
            aq2_sensoc2: translateInt(row['aq2.sensoc2']),
            aq2_sensod1: translateSimpleEnum(row['aq2.sensod1']),
            aq2_sensod2: translateInt(row['aq2.sensod2']),
            aq2_sensoe1: translateSimpleEnum(row['aq2.sensoe1']),
            aq2_sensoe2: translateInt(row['aq2.sensoe2']),
            aq2_sensof1: translateSimpleEnum(row['aq2.sensof1']),
            aq2_sensof2: translateInt(row['aq2.sensof2']),
            aq2_sensog1: translateSimpleEnum(row['aq2.sensog1']),
            aq2_sensog2: translateInt(row['aq2.sensog2']),
            aq2_sensoh1: translateSimpleEnum(row['aq2.sensoh1']),
            aq2_sensoh2: translateInt(row['aq2.sensoh2']),
            aq2_prot: translateSimpleEnum(row['aq2.prot']),
            aq2_protart1: translateSimpleEnum(row['aq2.protart1']),
            aq2_protart2: translateInt(row['aq2.protart2']),
            aq2_protcard1: translateSimpleEnum(row['aq2.protcard1']),
            aq2_protcard2: translateInt(row['aq2.protcard2']),
            aq2_protaud1: translateSimpleEnum(row['aq2.protaud1']),
            aq2_protaud2: translateInt(row['aq2.protaud2']),
            aq2_protdent1: translateSimpleEnum(row['aq2.protdent1']),
            aq2_protdent2: translateInt(row['aq2.protdent2']),
            aq2_chir: translateSimpleEnum(row['aq2.chir']),
            aq2_chirtxt: row['aq2.chirtxt'] || null,
            aq2_allerg: translateSimpleEnum(row['aq2.allerg']),
            aq2_allergtxt: row['aq2.allergtxt'] || null,
            aq2_atcdfam1: translateSimpleEnum(row['aq2.atcdfam1']),
            aq2_atcdfam2: translateSimpleEnum(row['aq2.atcdfam2']),
            aq2_atcdfam3: translateSimpleEnum(row['aq2.atcdfam3']),
            aq2_atcdfam4: translateSimpleEnum(row['aq2.atcdfam4']),
            aq2_atcdfam5: translateSimpleEnum(row['aq2.atcdfam5']),
            aq2_atcdfam6: translateSimpleEnum(row['aq2.atcdfam6']),
            aq2_atcdfam7: translateSimpleEnum(row['aq2.atcdfam7']),
            aq2_atcdfam8: translateSimpleEnum(row['aq2.atcdfam8']),
            aq2_atcdfam9: translateSimpleEnum(row['aq2.atcdfam9']),
            aq2_atcdfam10: translateSimpleEnum(row['aq2.atcdfam10']),
            aq2_atcdfam11: translateSimpleEnum(row['aq2.atcdfam11']),
            aq2_atcdfam12: translateSimpleEnum(row['aq2.atcdfam12']),
            aq2_atcdfam12prec: row['aq2.atcdfam12prec'] || null,
            aq2_med1: translateSimpleEnum(row['aq2.med1']),
            aq2_med2: translateSimpleEnum(row['aq2.med2']),
            aq2_med11: translateSimpleEnum(row['aq2.med11']),
            aq2_med12: translateSimpleEnum(row['aq2.med12']),
            aq2_med13: translateSimpleEnum(row['aq2.med13']),
            aq2_med5: translateSimpleEnum(row['aq2.med5']),
            aq2_medmed: row['aq2.medmed'] || null,
            aq2_med6: translateSimpleEnum(row['aq2.med6']),
            aq2_med7: translateSimpleEnum(row['aq2.med7']),
            aq2_med8: translateSimpleEnum(row['aq2.med8']),
            aq2_med9: translateSimpleEnum(row['aq2.med9']),
            aq2_med10: translateSimpleEnum(row['aq2.med10']),
            aq2_cres1: translateSimpleEnum(row['aq2.cres1']),
            aq2_cres2: translateSimpleEnum(row['aq2.cres2']),
            aq2_cres3: translateSimpleEnum(row['aq2.cres3']),
            aq2_cres4: translateSimpleEnum(row['aq2.cres4']),
            aq2_dnut1: translateSimpleEnum(row['aq2.dnut1']),
            aq2_dnut2: translateSimpleEnum(row['aq2.dnut2']),
            aq2_dnut3: translateSimpleEnum(row['aq2.dnut3']),
            aq2_dnut4: translateSimpleEnum(row['aq2.dnut4']),
            aq2_dnut5: translateSimpleEnum(row['aq2.dnut5']),
            aq2_dnut6: translateSimpleEnum(row['aq2.dnut6']),
            aq2_dnut7: translateSimpleEnum(row['aq2.dnut7']),
            aq2_peau: translateSimpleEnum(row['aq2.peau']),
            aq2_rein1: translateSimpleEnum(row['aq2.rein1']),
            aq2_rein2: translateSimpleEnum(row['aq2.rein2']),
            aq2_rein3: translateSimpleEnum(row['aq2.rein3']),
            aq2_rein4: translateSimpleEnum(row['aq2.rein4']),
            aq2_rein5: translateSimpleEnum(row['aq2.rein5']),
            aq2_rein6: translateSimpleEnum(row['aq2.rein6']),
            aq2_fem1: translateSimpleEnum(row['aq2.fem1']),
            aq2_fem2: translateSimpleEnum(row['aq2.fem2']),
            aq2_nerv: translateSimpleEnum(row['aq2.nerv']),
            aq2_cogn1: translateSimpleEnum(row['aq2.cogn1']),
            aq2_cogn2: translateSimpleEnum(row['aq2.cogn2']),
            aq2_cogn3: translateSimpleEnum(row['aq2.cogn3']),
            aq2_cogn4: translateSimpleEnum(row['aq2.cogn4']),
            aq2_cogn5: translateSimpleEnum(row['aq2.cogn5']),
            aq2_cogn6: translateSimpleEnum(row['aq2.cogn6']),
            aq2_cogn7: translateSimpleEnum(row['aq2.cogn7']),
            aq2_cogn8: translateSimpleEnum(row['aq2.cogn8']),
            aq2_chute1: translateSimpleEnum(row['aq2.chute1']),
            aq2_chute2: translateSimpleEnum(row['aq2.chute2']),
            aq2_chute3: translateSimpleEnum(row['aq2.chute3']),
            aq2_chute4: translateSimpleEnum(row['aq2.chute4']),
            aq2_chute5: translateSimpleEnum(row['aq2.chute5']),
            aq2_chute6: translateSimpleEnum(row['aq2.chute6']),
            aq2_chute7: translateSimpleEnum(row['aq2.chute7']),
            aq2_chute8: translateSimpleEnum(row['aq2.chute8']),
            aq2_chute9: translateSimpleEnum(row['aq2.chute9']),
            aq2_fsenso1: translateSimpleEnum(row['aq2.fsenso1']),
            aq2_fsenso2: translateSimpleEnum(row['aq2.fsenso2']),
            aq2_fsenso3: translateSimpleEnum(row['aq2.fsenso3']),
            aq2_fsenso4: translateSimpleEnum(row['aq2.fsenso4']),
            aq2_fsenso5: translateSimpleEnum(row['aq2.fsenso5']),
            demo_dmo_prec: translateSimpleEnum(row['demo.dmo_prec']),
            demo_dmo_prec_date: row['demo.dmo_prec_date'] || null,
            demo_dmo_prec_results: row['demo.dmo_prec_results'] || null,
            demo_realise: translateMultiEnum(row['demo.realise']),
            demo_realise_raison: translateSimpleEnum(row['demo.realise_raison']),
            demo_realise_raison_autre: row['demo.realise_raison_autre'] || null,
            demo_dose_totale_recue: translateFloat(row['demo.dose_totale_recue']),
            demo_dmo_l1: translateFloat(row['demo.dmo_l1']),
            demo_dmo_l2: translateFloat(row['demo.dmo_l2']),
            demo_dmo_l3: translateFloat(row['demo.dmo_l3']),
            demo_dmo_l4: translateFloat(row['demo.dmo_l4']),
            demo_dmo_rachis: translateFloat(row['demo.dmo_rachis']),
            demo_dmo_hanche_site: translateSimpleEnum(row['demo.dmo_hanche_site']),
            demo_dmo_col: translateFloat(row['demo.dmo_col']),
            demo_dmo_hanche: translateFloat(row['demo.dmo_hanche']),
            demo_dmo_avbras_site: translateSimpleEnum(row['demo.dmo_avbras_site']),
            demo_dmo_avb1: translateFloat(row['demo.dmo_avb1']),
            demo_dmo_avb2: translateFloat(row['demo.dmo_avb2']),
            demo_dmo_corps: translateFloat(row['demo.dmo_corps']),
            demo_dxa_mg_totale: translateInt(row['demo.dxa_mg_totale']),
            demo_dxa_mg_pct: translateFloat(row['demo.dxa_mg_pct']),
            demo_dxa_vat: translateInt(row['demo.dxa_vat']),
            demo_dxa_indice_mm: translateFloat(row['demo.dxa_indice_mm']),
            demo_frax_hanche: translateFloat(row['demo.frax_hanche']),
            demo_frax_majeur: translateFloat(row['demo.frax_majeur']),
            demo_commentaires: row['demo.commentaires'] || null,
            ems_mob0: row['ems.mob0'] || null,
            ems_objectifs_sante: translateMultiEnum(row['ems.objectifs_sante']),
            ems_objectifs_activite: translateMultiEnum(row['ems.objectifs_activite']),
            ems_objectifs_sante_autre: row['ems.objectifs_sante_autre'] || null,
            ems_objectifs_activite_autre: row['ems.objectifs_activite_autre'] || null,
            ems_auto1: translateSimpleEnum(row['ems.auto1']),
            ems_auto2: translateSimpleEnum(row['ems.auto2']),
            ems_pratique_activites: translateSimpleEnum(row['ems.pratique_activites']),
            ems_act1: translateSimpleEnum(row['ems.act1']),
            ems_act1_freq: translateSimpleEnum(row['ems.act1_freq']),
            ems_act1_temps: translateSimpleEnum(row['ems.act1_temps']),
            ems_act1_intensite: translateSimpleEnum(row['ems.act1_intensite']),
            ems_act2: translateSimpleEnum(row['ems.act2']),
            ems_act2_freq: translateSimpleEnum(row['ems.act2_freq']),
            ems_act2_temps: translateSimpleEnum(row['ems.act2_temps']),
            ems_act2_intensite: translateSimpleEnum(row['ems.act2_intensite']),
            ems_act3: translateSimpleEnum(row['ems.act3']),
            ems_act3_freq: translateSimpleEnum(row['ems.act3_freq']),
            ems_act3_temps: translateSimpleEnum(row['ems.act3_temps']),
            ems_act3_intensite: translateSimpleEnum(row['ems.act3_intensite']),
            ems_act4: translateSimpleEnum(row['ems.act4']),
            ems_act4_freq: translateSimpleEnum(row['ems.act4_freq']),
            ems_act4_temps: translateSimpleEnum(row['ems.act4_temps']),
            ems_act4_intensite: translateSimpleEnum(row['ems.act4_intensite']),
            ems_act5: translateSimpleEnum(row['ems.act5']),
            ems_act5_freq: translateSimpleEnum(row['ems.act5_freq']),
            ems_act5_temps: translateSimpleEnum(row['ems.act5_temps']),
            ems_act5_intensite: translateSimpleEnum(row['ems.act5_intensite']),
            ems_act6: translateSimpleEnum(row['ems.act6']),
            ems_act6_freq: translateSimpleEnum(row['ems.act6_freq']),
            ems_act6_temps: translateSimpleEnum(row['ems.act6_temps']),
            ems_act6_intensite: translateSimpleEnum(row['ems.act6_intensite']),
            ems_act7: translateSimpleEnum(row['ems.act7']),
            ems_act7_freq: translateSimpleEnum(row['ems.act7_freq']),
            ems_act7_temps: translateSimpleEnum(row['ems.act7_temps']),
            ems_act7_intensite: translateSimpleEnum(row['ems.act7_intensite']),
            ems_act8: translateSimpleEnum(row['ems.act8']),
            ems_act8_freq: translateSimpleEnum(row['ems.act8_freq']),
            ems_act8_temps: translateSimpleEnum(row['ems.act8_temps']),
            ems_act8_intensite: translateSimpleEnum(row['ems.act8_intensite']),
            ems_act9: translateSimpleEnum(row['ems.act9']),
            ems_act9_freq: translateSimpleEnum(row['ems.act9_freq']),
            ems_act9_temps: translateSimpleEnum(row['ems.act9_temps']),
            ems_act9_intensite: translateSimpleEnum(row['ems.act9_intensite']),
            ems_act10: translateSimpleEnum(row['ems.act10']),
            ems_act10_freq: translateSimpleEnum(row['ems.act10_freq']),
            ems_act10_temps: translateSimpleEnum(row['ems.act10_temps']),
            ems_act10_intensite: translateSimpleEnum(row['ems.act10_intensite']),
            ems_act_autre: row['ems.act_autre'] || null,
            ems_freins: translateMultiEnum(row['ems.freins']),
            ems_freins_autre: row['ems.freins_autre'] || null,
            ems_temps_assis_h: translateInt(row['ems.temps_assis_h']),
            ems_temps_assis_min: translateInt(row['ems.temps_assis_min']),
            ems_assis_2h_continu: translateSimpleEnum(row['ems.assis_2h_continu']),
            ems_test_handgrip_realise: translateSimpleEnum(row['ems.test_handgrip_realise']),
            ems_test_handgrip_realise_raison: translateSimpleEnum(row['ems.test_handgrip_realise_raison']),
            ems_test_handgrip_realise_autre: row['ems.test_handgrip_realise_autre'] || null,
            ems_test_handgrip: translateFloat(row['ems.test_handgrip']),
            ems_test_handgrip_main: translateSimpleEnum(row['ems.test_handgrip_main']),
            ems_test_unipod_realise: translateSimpleEnum(row['ems.test_unipod_realise']),
            ems_test_unipod_realise_raison: translateSimpleEnum(row['ems.test_unipod_realise_raison']),
            ems_test_unipod_realise_autre: row['ems.test_unipod_realise_autre'] || null,
            ems_test_unipod: translateFloat(row['ems.test_unipod']),
            ems_test_unipod_membre: translateSimpleEnum(row['ems.test_unipod_membre']),
            ems_test_vit4_realise: translateSimpleEnum(row['ems.test_vit4_realise']),
            ems_test_vit4_realise_raison: translateSimpleEnum(row['ems.test_vit4_realise_raison']),
            ems_test_vit4_realise_autre: row['ems.test_vit4_realise_autre'] || null,
            ems_test_vit4: translateFloat(row['ems.test_vit4']),
            ems_test_vit4_posture: row['ems.test_vit4_posture'] || null,
            ems_test_vit4_aide: translateSimpleEnum(row['ems.test_vit4_aide']),
            ems_test_vit4_aide_txt: row['ems.test_vit4_aide_txt'] || null,
            ems_test_timeup_realise: translateSimpleEnum(row['ems.test_timeup_realise']),
            ems_test_timeup_realise_raison: translateSimpleEnum(row['ems.test_timeup_realise_raison']),
            ems_test_timeup_realise_autre: row['ems.test_timeup_realise_autre'] || null,
            ems_test_timeup: translateFloat(row['ems.test_timeup']),
            ems_test_timeup_gestuel: translateSimpleEnum(row['ems.test_timeup_gestuel']),
            ems_test_timeup_equilibre: translateSimpleEnum(row['ems.test_timeup_equilibre']),
            ems_test_timeup_observ: translateMultiEnum(row['ems.test_timeup_observ']),
            ems_test_timeup_aide: translateSimpleEnum(row['ems.test_timeup_aide']),
            ems_test_timeup_aide_txt: row['ems.test_timeup_aide_txt'] || null,
            ems_test_getup_realise: translateSimpleEnum(row['ems.test_getup_realise']),
            ems_test_getup_realise_raison: translateSimpleEnum(row['ems.test_getup_realise_raison']),
            ems_test_getup_realise_autre: row['ems.test_getup_realise_autre'] || null,
            ems_test_getup: translateSimpleEnum(row['ems.test_getup']),
            ems_test_getup_comm: row['ems.test_getup_comm'] || null,
            ems_test_getup_aide: translateSimpleEnum(row['ems.test_getup_aide']),
            ems_test_getup_aide_txt: row['ems.test_getup_aide_txt'] || null,
            ems_eval1: translateSimpleEnum(row['ems.eval1']),
            ems_eval2: translateSimpleEnum(row['ems.eval2']),
            ems_eval3: translateSimpleEnum(row['ems.eval3']),
            ems_eval4: translateSimpleEnum(row['ems.eval4']),
            ems_eval4_raison: translateMultiEnum(row['ems.eval4_raison']),
            ems_eval4_raison_autre: row['ems.eval4_raison_autre'] || null,
            ems_dispo_matin: translateMultiEnum(row['ems.dispo_matin']),
            ems_dispo_midi: translateMultiEnum(row['ems.dispo_midi']),
            ems_dispo_apresmidi: translateMultiEnum(row['ems.dispo_apresmidi']),
            ems_dispo_soiree: translateMultiEnum(row['ems.dispo_soiree']),
            ems_synthese: row['ems.synthese'] || null,
            ems_coaching_osteo1: translateSimpleEnum(row['ems.coaching_osteo1']),
            ems_coaching_osteo1_autre: row['ems.coaching_osteo1_autre'] || null,
            ems_coaching_osteo2: translateSimpleEnum(row['ems.coaching_osteo2']),
            ems_coaching_osteo2_autre: row['ems.coaching_osteo2_autre'] || null,
            ems_coaching_sarco: translateSimpleEnum(row['ems.coaching_sarco']),
            ems_coaching_sarco_autre: row['ems.coaching_sarco_autre'] || null,
            ems_coaching_conseils: translateMultiEnum(row['ems.coaching_conseils']),
            ems_coaching_autres_autre: row['ems.coaching_autres_autre'] || null,
            ems_coaching_proposition: translateSimpleEnum(row['ems.coaching_proposition']),
            ems_coaching_motivation: translateSimpleEnum(row['ems.coaching_motivation']),
            ems_coaching_ext: translateSimpleEnum(row['ems.coaching_ext']),
            ems_mob14: translateSimpleEnum(row['ems.mob14']),
            audition_audio1: translateSimpleEnum(row['audition.audio1']),
            audition_audio2: translateSimpleEnum(row['audition.audio2']),
            audition_audio2autre: row['audition.audio2autre'] || null,
            audition_audio9: translateInt(row['audition.audio9']),
            audition_audio3: translateInt(row['audition.audio3']),
            audition_audio10: translateInt(row['audition.audio10']),
            audition_audio4: translateInt(row['audition.audio4']),
            audition_audio11: translateInt(row['audition.audio11']),
            audition_audio5: translateInt(row['audition.audio5']),
            audition_audio12: translateInt(row['audition.audio12']),
            audition_audio6: translateInt(row['audition.audio6']),
            audition_audio16: translateSimpleEnum(row['audition.audio16']),
            audition_audio17: translateSimpleEnum(row['audition.audio17']),
            audition_audio17autre: row['audition.audio17autre'] || null,
            audition_audio15: translateFloat(row['audition.audio15']),
            audition_audio_comm: row['audition.audio_comm'] || null,
            vision_vis1: translateSimpleEnum(row['vision.vis1']),
            vision_vis1b: translateSimpleEnum(row['vision.vis1b']),
            vision_vis2: translateSimpleEnum(row['vision.vis2']),
            vision_vis2b: translateSimpleEnum(row['vision.vis2b']),
            vision_vis2bautre: row['vision.vis2bautre'] || null,
            vision_vis5: translateInt(row['vision.vis5']),
            vision_vis4: translateInt(row['vision.vis4']),
            vision_vis6: translateInt(row['vision.vis6']),
            vision_vis8: translateInt(row['vision.vis8']),
            vision_vis7: translateInt(row['vision.vis7']),
            vision_vis9: translateInt(row['vision.vis9']),
            vision_visio1: translateSimpleEnum(row['vision.visio1']),
            vision_visio2: translateSimpleEnum(row['vision.visio2']),
            vision_visio2autre: row['vision.visio2autre'] || null,
            vision_visio3: translateInt(row['vision.visio3']),
            vision_visio6: translateInt(row['vision.visio6']),
            vision_visio4: translateInt(row['vision.visio4']),
            vision_visio7: translateInt(row['vision.visio7']),
            vision_visio5: translateInt(row['vision.visio5']),
            vision_visio8: translateInt(row['vision.visio8']),
            vision_tono1: translateSimpleEnum(row['vision.tono1']),
            vision_tono2: translateSimpleEnum(row['vision.tono2']),
            vision_tono2autre: row['vision.tono2autre'] || null,
            vision_tono9: translateFloat(row['vision.tono9']),
            vision_tono11: translateInt(row['vision.tono11']),
            vision_tono10: translateFloat(row['vision.tono10']),
            vision_tono12: translateInt(row['vision.tono12']),
            vision_retino1: translateSimpleEnum(row['vision.retino1']),
            vision_retino2: translateSimpleEnum(row['vision.retino2']),
            vision_retino2autre: row['vision.retino2autre'] || null,
            vision_retino3: translateMultiEnum(row['vision.retino3']),
            vision_retino4: row['vision.retino4'] || null,
            vision_vis_comm: row['vision.vis_comm'] || null,
            respi_realise: translateSimpleEnum(row['respi.realise']),
            respi_realise_raison: translateSimpleEnum(row['respi.realise_raison']),
            respi_realise_raison_autre: row['respi.realise_raison_autre'] || null,
            respi_spiro_qualite1: translateSimpleEnum(row['respi.spiro_qualite1']),
            respi_champ_n223: translateSimpleEnum(row['respi.champ_n223']),
            respi_vems_theorique: translateFloat(row['respi.vems_theorique']),
            respi_vems_limite: translateFloat(row['respi.vems_limite']),
            respi_vems: translateFloat(row['respi.vems']),
            respi_cvf_theorique: translateFloat(row['respi.cvf_theorique']),
            respi_cvf_limite: translateFloat(row['respi.cvf_limite']),
            respi_cvf: translateFloat(row['respi.cvf']),
            respi_def2575_theorique: translateFloat(row['respi.def2575_theorique']),
            respi_def2575_limite: translateFloat(row['respi.def2575_limite']),
            respi_def2575: translateFloat(row['respi.def2575']),
            respi_demm25: translateInt(row['respi.demm25']),
            respi_demm50: translateInt(row['respi.demm50']),
            respi_demm75: translateInt(row['respi.demm75']),
            respi_demm2575: translateInt(row['respi.demm2575']),
            respi_dep: translateInt(row['respi.dep']),
            respi_comm: row['respi.comm'] || null,
            constantes_taille: translateInt(row['constantes.taille']),
            constantes_poids: translateFloat(row['constantes.poids']),
            constantes_tour_taille: translateInt(row['constantes.tour_taille']),
            constantes_tour_hanches: translateInt(row['constantes.tour_hanches']),
            constantes_explcv_realise: translateSimpleEnum(row['constantes.explcv_realise']),
            constantes_explcv_realise_raison: translateSimpleEnum(row['constantes.explcv_realise_raison']),
            constantes_explcv_realise_raison_autre: row['constantes.explcv_realise_raison_autre'] || null,
            constantes_explcv2: translateInt(row['constantes.explcv2']),
            constantes_explcv3: translateInt(row['constantes.explcv3']),
            constantes_explcv4: translateInt(row['constantes.explcv4']),
            constantes_explcv5: translateInt(row['constantes.explcv5']),
            constantes_explcv6: translateInt(row['constantes.explcv6']),
            constantes_explcv7: translateInt(row['constantes.explcv7']),
            constantes_explcv2b: translateInt(row['constantes.explcv2b']),
            constantes_explcv3b: translateInt(row['constantes.explcv3b']),
            constantes_explcv4b: translateInt(row['constantes.explcv4b']),
            constantes_explcv5b: translateInt(row['constantes.explcv5b']),
            constantes_explcv6b: translateInt(row['constantes.explcv6b']),
            constantes_explcv7b: translateInt(row['constantes.explcv7b']),
            constantes_explcv8: translateInt(row['constantes.explcv8']),
            constantes_explcv9: translateInt(row['constantes.explcv9']),
            constantes_explcv10: translateInt(row['constantes.explcv10']),
            constantes_explcv11: translateInt(row['constantes.explcv11']),
            constantes_explcv12: translateInt(row['constantes.explcv12']),
            constantes_explcv13: translateInt(row['constantes.explcv13']),
            constantes_explcv14: translateInt(row['constantes.explcv14']),
            constantes_explcv15: translateInt(row['constantes.explcv15']),
            constantes_explcv16: translateInt(row['constantes.explcv16']),
            constantes_explcv_realise_vop: translateSimpleEnum(row['constantes.explcv_realise_vop']),
            constantes_explcv_realise_vop_raison: translateSimpleEnum(row['constantes.explcv_realise_vop_raison']),
            constantes_explcv_realise_vop_raison_autre: row['constantes.explcv_realise_vop_raison_autre'] || null,
            constantes_explcv17: translateFloat(row['constantes.explcv17']),
            constantes_explcv_realise_ager: translateSimpleEnum(row['constantes.explcv_realise_ager']),
            constantes_explcv_realise_ager_raison: translateSimpleEnum(row['constantes.explcv_realise_ager_raison']),
            constantes_explcv_realise_ager_raison_autre: row['constantes.explcv_realise_ager_raison_autre'] || null,
            constantes_cv_glyc: translateFloat(row['constantes.cv_glyc']),
            diet_evaluateur: row['diet.evaluateur'] || null,
            diet_repas_par_jour: translateInt(row['diet.repas_par_jour']),
            diet_collations_par_jour: translateInt(row['diet.collations_par_jour']),
            diet_rythme_regulier: translateSimpleEnum(row['diet.rythme_regulier']),
            diet_modes_alimentaires: translateMultiEnum(row['diet.modes_alimentaires']),
            diet_modes_alimentaires_autre: row['diet.modes_alimentaires_autre'] || null,
            diet_diversite_alimentaire: translateSimpleEnum(row['diet.diversite_alimentaire']),
            diet_grignotage: translateSimpleEnum(row['diet.grignotage']),
            diet_grignotage_type: translateSimpleEnum(row['diet.grignotage_type']),
            diet_apports_proteines: translateSimpleEnum(row['diet.apports_proteines']),
            diet_apports_calcium: translateSimpleEnum(row['diet.apports_calcium']),
            diet_apports_global: translateSimpleEnum(row['diet.apports_global']),
            diet_albuminemie: translateInt(row['diet.albuminemie']),
            diet_interet1: translateSimpleEnum(row['diet.interet1']),
            diet_interet2: translateSimpleEnum(row['diet.interet2']),
            diet_preparation1: translateSimpleEnum(row['diet.preparation1']),
            diet_preparation2: translateSimpleEnum(row['diet.preparation2']),
            diet_preparation3: translateSimpleEnum(row['diet.preparation3']),
            diet_plaisir_manger: translateSimpleEnum(row['diet.plaisir_manger']),
            diet_plaisir_causes1: translateMultiEnum(row['diet.plaisir_causes1']),
            diet_plaisir_causes2: translateMultiEnum(row['diet.plaisir_causes2']),
            diet_signaux1: translateSimpleEnum(row['diet.signaux1']),
            diet_signaux2: translateSimpleEnum(row['diet.signaux2']),
            diet_signaux3: translateSimpleEnum(row['diet.signaux3']),
            diet_tendances_adaptees: translateSimpleEnum(row['diet.tendances_adaptees']),
            diet_tendances_inadaptees: translateSimpleEnum(row['diet.tendances_inadaptees']),
            diet_tendances_types: translateMultiEnum(row['diet.tendances_types']),
            diet_poids_estime_6mois: translateInt(row['diet.poids_estime_6mois']),
            diet_variation_volontaire: translateSimpleEnum(row['diet.variation_volontaire']),
            diet_motiv_envie: translateSimpleEnum(row['diet.motiv_envie']),
            diet_motiv_pret: translateSimpleEnum(row['diet.motiv_pret']),
            diet_synthese: row['diet.synthese'] || null,
            diet_objectifs: row['diet.objectifs'] || null,
            diet_proposition_coaching: translateSimpleEnum(row['diet.proposition_coaching']),
            diet_forme_coaching: translateSimpleEnum(row['diet.forme_coaching']),
            rdv_pl_financeur: translateSimpleEnum(row['rdv.pl_financeur']),
            rdv_balc_entreprise: translateSimpleEnum(row['rdv.balc_entreprise']),
            rdv_plid: row['rdv.plid'] || null,
            rdv_statut_rdv: translateSimpleEnum(row['rdv.statut_rdv']),
            rdv_date: row['rdv.date'] || null,
            consultant_sexe: row['consultant.sexe'] || null,
            consultant_nom: row['consultant.nom'] || null,
            consultant_nom_jeune_fille: row['consultant.nom_jeune_fille'] || null,
            consultant_prenom: row['consultant.prenom'] || null,
            consultant_date_naissance: row['consultant.date_naissance'] || null,
            consultant_ville_naissance: row['consultant.ville_naissance'] || null,
            consultant_adresse: row['consultant.adresse'] || null,
            consultant_code_postal: row['consultant.code_postal'] || null,
            consultant_ville: row['consultant.ville'] || null,
            consultant_tel: row['consultant.tel'] || null,
            consultant_mail: row['consultant.mail'] || null,
            consultant_mail_entreprise: row['consultant.mail_entreprise'] || null,
            consultant_numero_secu_consultant: row['consultant.numero_secu_consultant'] || null,
            consultant_nom_med_consultant: row['consultant.nom_med_consultant'] || null,
            consultant_prenom_med_consultant: row['consultant.prenom_med_consultant'] || null,
            consultant_ville_med_consultant: row['consultant.ville_med_consultant'] || null,
            consultant_med_spec_consultant: row['consultant.med_spec_consultant'] || null,
            consultant_nom_pharma_consultant: row['consultant.nom_pharma_consultant'] || null,
            consultant_ville_pharma_consultant: row['consultant.ville_pharma_consultant'] || null,
            consultant_transmission_resultats: translateSimpleEnum(row['consultant.transmission_resultats'])
        };

        // FIXME: Wrong shortcuts but acceptable for now
        row2.rdv_age = translateInt(row['consultant.age']);
        row2.bio_albuminemie = 40;

        // Simplified neuropsy variables
        row2.neuropsy_moca = translateFloat(row['neuropsy.score_moca']),
        row2.neuropsy_tmta = translateFloat(row['neuropsy.score_tmta_temps']),
        row2.neuropsy_lecture = translateFloat(row['neuropsy.score_lecture_temps']),
        row2.neuropsy_tmtb = translateFloat(row['neuropsy.score_tmtb_temps']),
        row2.neuropsy_interf = translateFloat(row['neuropsy.score_interf_temps1']),
        row2.neuropsy_slc = translateFloat(row['neuropsy.seqlc_score_brut']),
        row2.neuropsy_animx = translateFloat(row['neuropsy.score_flu1_correct']),
        row2.neuropsy_p = translateFloat(row['neuropsy.score_flu2_correct']),
        row2.neuropsy_rl = translateFloat(row['neuropsy.score_3rl']) || translateFloat(row['neuropsy.score_2rl']),
        row2.neuropsy_rt = translateFloat(row['neuropsy.score_3rt']) || translateFloat(row['neuropsy.score_2rt'])

        // Simplified EMS variables
        row2.ems_temps_assis_jour = parseInt(row['ems.temps_assis_jour_h']) * 60 +
                                    parseInt(row['ems.temps_assis_jour_min'])
        for (let i = 1; i <= 10; i++) {
            switch (translateSimpleEnum(row[`ems.act${i}_temps`])) {
                case 0: { row2[`ems_act${i}_duree`] = 15; } break;
                case 1: { row2[`ems_act${i}_duree`] = 30; } break;
                case 2: { row2[`ems_act${i}_duree`] = 45; } break;
                case 3: { row2[`ems_act${i}_duree`] = 60; } break;
                case 4: { row2[`ems_act${i}_duree`] = 90; } break;
                case 5: { row2[`ems_act${i}_duree`] = 120; } break;
                case 6: { row2[`ems_act${i}_duree`] = 180; } break;
                case null: { row2[`ems_act${i}_duree`] = null; } break;
            }
        }

        return row2;
    }

    this.readFileAsync = function(file, config) {
        Papa.parse(file, {
            header: true,
            encoding: config.encoding,
            chunk: ret => {
                for (let row of ret.data) {
                    row = translateRow(row);
                    if (row.rdv_plid && row.consultant_sexe)
                        config.step(row);
                }
            },
            complete: config.complete
        });
    };

    return this;
}).call({});
