# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see https://www.gnu.org/licenses/.

- name: Install packages
  package:
    update_cache: yes
    pkg:
      - nginx
      - python3-certbot-nginx
      - logrotate
    state: latest
  become: yes

- name: Enable services
  service:
    name: '{{ item }}'
    enabled: yes
  loop:
    - nginx
    - logrotate
  become: yes

- name: Prepare NGINX and SSL directories
  file:
    path: '{{ item }}'
    state: directory
    owner: root
    group: root
    mode: '0755'
  loop:
    - /opt/nginx
    - /opt/nginx/ssl
    - /opt/nginx/ssl/internal
  become: yes

- name: Generate Diffie-Helman parameters
  command:
    cmd: 'openssl dhparam -out /opt/nginx/ssl/dhparam.pem 2048'
    creates: /opt/nginx/ssl/dhparam.pem
  become: yes

- name: Generate private CA and certificates
  include_tasks: ssl_internal.yml
  when: 'not ansible_check_mode'

- name: Configure NGINX
  template:
    src: 'nginx_{{ nginx_mode }}.conf.j2'
    dest: /opt/nginx/nginx.conf
  register: nginx_config
  become: yes

- name: Link NGINX configuration
  file:
    path: /etc/nginx/nginx.conf
    state: link
    src: /opt/nginx/nginx.conf
    force: yes
    follow: no
  become: yes

- name: Configure certbot
  include_tasks: ssl_certbot.yml
  when: 'nginx_mode == "single" or nginx_mode == "front"'

- name: Reload NGINX
  service:
    name: nginx
    state: reloaded
  when: 'not ansible_check_mode'
  become: yes
