// SPDX-License-Identifier: MIT
// SPDX-FileCopyrightText: 2026 Niels Martignène <niels.martignene@protonmail.com>

#if !defined(PRIMITIVE)
    #error Please define PRIMITIVE() before including primitives.inc
#endif

PRIMITIVE(Void)
PRIMITIVE(Bool)
PRIMITIVE(Int8)
PRIMITIVE(UInt8)
PRIMITIVE(Int16)
PRIMITIVE(Int16S)  // Keep behind Int16
PRIMITIVE(UInt16)
PRIMITIVE(UInt16S) // Keep behind UInt16
PRIMITIVE(Int32)
PRIMITIVE(Int32S)  // Keep behind Int32
PRIMITIVE(UInt32)
PRIMITIVE(UInt32S) // Keep behind UInt32
PRIMITIVE(Int64)
PRIMITIVE(Int64S)  // Keep behind Int64
PRIMITIVE(UInt64)
PRIMITIVE(UInt64S) // Keep behind UInt64
PRIMITIVE(String)
PRIMITIVE(String16)
PRIMITIVE(String32)
PRIMITIVE(Pointer)
PRIMITIVE(Record)
PRIMITIVE(Union)
PRIMITIVE(Array)
PRIMITIVE(Float32)
PRIMITIVE(Float64)
PRIMITIVE(Callback)
PRIMITIVE(Prototype)

#undef PRIMITIVE
