all:
  hosts:
    host1:
      ansible_host: 192.168.33.20
      ansible_port: 22
      ansible_user: ansible
      ansible_ssh_private_key_file: .vagrant/machines/host1/virtualbox/private_key
      ansible_python_interpreter: /usr/bin/python3

      nginx_public_addr: '{{ ansible_host }}'
      nginx_domains:
        - name: '{{ prometheus_public_addr }}'
          config: |
            ssl_client_certificate /opt/nginx/ssl/internal/ca.crt;
            ssl_verify_client on;
            ssl_verify_depth 2;

            {% for exporter in prometheus_exporters %}

            location /metrics/{{ exporter }} {
                allow {{ hostvars.monitor.nginx_public_addr }};
                deny all;

                proxy_set_header Host $host;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

                proxy_pass http://127.0.0.1:{{ prometheus_packages[exporter].port }}/metrics;
            }
            {% endfor %}
        - name: goupile1.pknet.local
          config: |
            location / {
                proxy_http_version 1.1;
                proxy_request_buffering off;
                proxy_buffering off;

                proxy_set_header Host $host;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

                proxy_pass http://unix:/run/goupile/goupile1.pknet.local.sock:;
            }
        - name: goupile2.pknet.local
          config: |
            location / {
                proxy_http_version 1.1;
                proxy_request_buffering off;
                proxy_buffering off;

                proxy_set_header Host $host;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

                proxy_pass http://unix:/run/goupile/goupile2.pknet.local.sock:;
            }

      goupile_commit: deploy_pknet
      goupile_domains:
        - name: goupile1.pknet.local
          archive_key: YyQHN671EI9hEixEcUjsIVQvfMcsKUEe888V1Qx8UBI= # Decryption: mfoMJb1Zv4hh68MZ8c8UjjMv5yAnY7dwxPrY2EcNTrU=
        - name: goupile2.pknet.local
          archive_key: aZmAwOf9E/3WwnhS1LCM1r54TLjog/d0hwM0k72ULmw= # Decryption: D55mv4rBOk/9WywLcS//Zb8k7jhcr+ZGYi+JoVKUrdQ=

      prometheus_public_addr: '{{ ansible_host }}'
      prometheus_exporters:
        - node_exporter
        - nginx_exporter

      borg_public_addr: '{{ ansible_host }}'
      borg_directories:
        - '{{ goupile_snapshot_path }}'
      borg_passphrase: 'borg!16/default_pwd'
      borg_time: '04:00' # Run after goupile snapshot

    backup:
      ansible_host: 192.168.33.28
      ansible_port: 22
      ansible_user: vagrant
      ansible_ssh_private_key_file: .vagrant/machines/backup/virtualbox/private_key
      ansible_python_interpreter: /usr/bin/python3

      nginx_public_addr: '{{ ansible_host }}'
      nginx_domains:
        - name: '{{ prometheus_public_addr }}'
          config: |
            ssl_client_certificate /opt/nginx/ssl/internal/ca.crt;
            ssl_verify_client on;
            ssl_verify_depth 2;

            {% for exporter in prometheus_exporters %}

            location /metrics/{{ exporter }} {
                allow {{ hostvars.monitor.nginx_public_addr }};
                deny all;

                proxy_set_header Host $host;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

                proxy_pass http://127.0.0.1:{{ prometheus_packages[exporter].port }}/metrics;
            }
            {% endfor %}

      prometheus_public_addr: '{{ ansible_host }}'
      prometheus_exporters:
        - node_exporter
        - nginx_exporter

      borg_public_addr: '{{ ansible_host }}'
      borg_server: yes

    monitor:
      ansible_host: 192.168.33.29
      ansible_port: 22
      ansible_user: vagrant
      ansible_ssh_private_key_file: .vagrant/machines/monitor/virtualbox/private_key
      ansible_python_interpreter: /usr/bin/python3

      nginx_public_addr: '{{ ansible_host }}'
      nginx_domains:
        - name: '{{ prometheus_public_addr }}'
          config: |
            ssl_client_certificate /opt/nginx/ssl/internal/ca.crt;
            ssl_verify_client on;
            ssl_verify_depth 2;

            {% for exporter in prometheus_exporters %}

            location /metrics/{{ exporter }} {
                allow {{ hostvars.monitor.nginx_public_addr }};
                deny all;

                proxy_set_header Host $host;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

                proxy_pass http://127.0.0.1:{{ prometheus_packages[exporter].port }}/metrics;
            }
            {% endfor %}
        - name: pknet-monitor.local
          config: |
            limit_req zone=default burst=100 nodelay;

            location /prometheus {
                proxy_set_header Host $host;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

                proxy_pass http://127.0.0.1:9090;
            }

            location / {
                proxy_set_header Host $host;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

                proxy_pass http://127.0.0.1:9200;
            }

      prometheus_public_addr: '{{ ansible_host }}'
      prometheus_exporters:
        - node_exporter
        - nginx_exporter
      prometheus_url: 'https://pknet-monitor.local/prometheus'
      grafana_url: 'https://pknet-monitor.local/'

      borg_public_addr: '{{ ansible_host }}'

