# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see https://www.gnu.org/licenses/.

- name: Install packages
  package:
    update_cache: yes
    pkg:
      - nginx
      - python3-certbot-nginx
    state: latest
  become: yes

- name: Enable NGINX
  service:
    name: nginx
    enabled: yes
  become: yes

- name: Prepare NGINX and SSL directories
  file:
    path: '{{ item.path }}'
    state: directory
    owner: root
    group: root
    mode: '{{ item.mode }}'
  loop:
    - path: /opt/nginx
      mode: '0755'
    - path: /opt/nginx/ssl
      mode: '0755'
    - path: /opt/nginx/ssl/internal
      mode: '0700'
  become: yes

- name: Link NGINX configuration
  file:
    path: /etc/nginx/nginx.conf
    state: link
    src: /opt/nginx/nginx.conf
    force: yes
  become: yes

- name: Generate Diffie-Helman parameters
  command:
    cmd: 'openssl dhparam -out /opt/nginx/ssl/dhparam.pem 2048'
    creates: /opt/nginx/ssl/dhparam.pem
  become: yes

- name: Generate private CA and certificates
  include_tasks: internal_ssl.yml
  when: 'not ansible_check_mode'

- name: Configure proxy host
  include_tasks: proxy.yml
  when: 'inventory_hostname == "proxy"'

- name: Configure server host
  include_tasks: server.yml
  when: 'inventory_hostname == "server"'

- name: Reload NGINX
  service:
    name: nginx
    state: reloaded
  when: 'not ansible_check_mode'
  become: yes
