# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see https://www.gnu.org/licenses/.

- name: Create local SSL folder for HDS certificate chain
  file:
    path: tmp_interhop_ssl
    state: directory
  delegate_to: localhost
  run_once: yes
  become: no

- name : Create SSL configuration files
  template:
    src: '{{ item }}.j2'
    dest: 'tmp_interhop_ssl/{{ item }}'
  loop:
    - ssl_ca.conf
    - ssl_proxy.conf
    - ssl_server.conf
  delegate_to: localhost
  run_once: yes
  become: no

- name: Generate CA and HDS certificates
  shell: |
    openssl genrsa -out tmp_interhop_ssl/ca.key 4096
    openssl req -x509 -new -key tmp_interhop_ssl/ca.key -config tmp_interhop_ssl/ssl_ca.conf -days 372 -out tmp_interhop_ssl/ca.crt
    openssl genrsa -out tmp_interhop_ssl/server.key 2048
    openssl req -new -key tmp_interhop_ssl/server.key -out tmp_interhop_ssl/server.csr -config tmp_interhop_ssl/ssl_server.conf
    openssl x509 -req -in tmp_interhop_ssl/server.csr -CA tmp_interhop_ssl/ca.crt -CAkey tmp_interhop_ssl/ca.key -CAcreateserial -out tmp_interhop_ssl/server.crt -days 372 -sha256 -extfile tmp_interhop_ssl/ssl_server.conf -extensions req_ext
    openssl genrsa -out tmp_interhop_ssl/proxy.key 2048
    openssl req -new -key tmp_interhop_ssl/proxy.key -out tmp_interhop_ssl/proxy.csr -config tmp_interhop_ssl/ssl_proxy.conf
    openssl x509 -req -in tmp_interhop_ssl/proxy.csr -CA tmp_interhop_ssl/ca.crt -CAkey tmp_interhop_ssl/ca.key -CAcreateserial -out tmp_interhop_ssl/proxy.crt -days 372 -sha256 -extfile tmp_interhop_ssl/ssl_proxy.conf -extensions req_ext
  delegate_to: localhost
  run_once: yes
  become: no

- name: Push internal keys and certificates
  copy:
    src: 'tmp_interhop_ssl/{{ item }}'
    dest: '/opt/nginx/ssl/internal/{{ item }}'
    owner: root
    group: root
    mode: '0600'
  loop:
    - ca.crt
    - '{{ inventory_hostname }}.key'
    - '{{ inventory_hostname }}.crt'
  become: yes

- name: Delete local SSL files
  file:
    path: tmp_interhop_ssl
    state: absent
  delegate_to: localhost
  run_once: yes
  become: no
