# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see https://www.gnu.org/licenses/.

nginx_public_addr: '{{ ansible_host }}'

nginx_domains:
  - name: '{{ prometheus_public_addr }}'
    config: |
      ssl_client_certificate /opt/nginx/ssl/internal/ca.crt;
      ssl_verify_client on;
      ssl_verify_depth 2;

      {% for exporter in prometheus_exporters %}

      location /metrics/{{ exporter }} {
          allow {{ hostvars.monitor.nginx_public_addr }};
          deny all;

          proxy_set_header Host $host;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

          proxy_pass http://127.0.0.1:{{ prometheus_packages[exporter].port }}/metrics;
      }
      {% endfor %}
  - name: anesth-lille.goupile.fr
    config: |
      location / {
          proxy_http_version 1.1;
          proxy_request_buffering off;
          proxy_buffering on;
          proxy_read_timeout 180;
          send_timeout 180;

          proxy_set_header Host $host;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

          proxy_pass http://unix:/run/goupile/anesth-lille.goupile.fr.sock:;
      }
    ssl_certbot_email: niels.martignene@protonmail.com
  - name: biosurv.goupile.fr
    config: |
      location / {
          proxy_http_version 1.1;
          proxy_request_buffering off;
          proxy_buffering on;
          proxy_read_timeout 180;
          send_timeout 180;

          proxy_set_header Host $host;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

          proxy_pass http://unix:/run/goupile/biosurv.goupile.fr.sock:;
      }
    ssl_certbot_email: niels.martignene@protonmail.com
  - name: cn2r.goupile.fr
    config: |
      location / {
          proxy_http_version 1.1;
          proxy_request_buffering off;
          proxy_buffering on;
          proxy_read_timeout 180;
          send_timeout 180;

          proxy_set_header Host $host;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

          proxy_pass http://unix:/run/goupile/cn2r.goupile.fr.sock:;
      }
    ssl_certbot_email: niels.martignene@protonmail.com
  - name: medita.goupile.fr
    config: |
      location / {
          proxy_http_version 1.1;
          proxy_request_buffering off;
          proxy_buffering on;
          proxy_read_timeout 180;
          send_timeout 180;

          proxy_set_header Host $host;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

          proxy_pass http://unix:/run/goupile/medita.goupile.fr.sock:;
      }
    ssl_certbot_email: niels.martignene@protonmail.com
  - name: test.goupile.fr
    config: |
      location / {
          proxy_http_version 1.1;
          proxy_request_buffering off;
          proxy_buffering on;
          proxy_read_timeout 180;
          send_timeout 180;

          proxy_set_header Host $host;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

          proxy_pass http://unix:/run/goupile/test.goupile.fr.sock:;
      }
    ssl_certbot_email: niels.martignene@protonmail.com

  - name: f2rsm.goupile.org
    config: |
      location / {
          proxy_http_version 1.1;
          proxy_request_buffering off;
          proxy_buffering on;
          proxy_read_timeout 180;
          send_timeout 180;

          proxy_set_header Host $host;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

          proxy_pass http://unix:/run/goupile/f2rsm.goupile.org.sock:;
      }

      location = /annuaire {
          rewrite ^([^.]*[^/])$ $1/ permanent;
      }
      location /annuaire/ {
          proxy_http_version 1.1;
          proxy_set_header Host koromix.dev;
          proxy_pass https://51.210.176.2/carto_2nps/;
      }
    ssl_certbot_email: niels.martignene@protonmail.com

  - name: thop.koromix.dev
    config: |
      location / {
          proxy_http_version 1.1;
          proxy_request_buffering off;
          proxy_buffering on;
          proxy_read_timeout 180;
          send_timeout 180;

          proxy_set_header Host $host;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

          proxy_pass http://unix:/run/thop/thop.sock:;
      }
    ssl_certbot_email: niels.martignene@protonmail.com
  - name: forparis.goupile.fr
    config: |
      location / {
          proxy_http_version 1.1;
          proxy_request_buffering off;
          proxy_buffering on;
          proxy_read_timeout 180;
          send_timeout 180;

          proxy_set_header Host $host;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

          proxy_pass http://unix:/run/goupile/forparis.goupile.fr.sock:;
      }
    ssl_certbot_email: niels.martignene@protonmail.com
  - name: goupile.interhop.org
    config: |
      location / {
          proxy_http_version 1.1;
          proxy_request_buffering off;
          proxy_buffering on;
          proxy_read_timeout 180;
          send_timeout 180;

          proxy_set_header Host $host;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

          proxy_pass http://unix:/run/goupile/goupile.interhop.org.sock:;
      }
    ssl_certbot_email: niels.martignene@protonmail.com
