# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see https://www.gnu.org/licenses/.
nginx_public_addr: '{{ ansible_host }}'

nginx_domains:
  - name: '{{ prometheus_public_addr }}'
    # ssl_certbot_email: niels.martignene@protonmail.com
    config: |
      ssl_client_certificate /opt/nginx/ssl/internal/ca.crt;
      ssl_verify_client on;
      ssl_verify_depth 2;

      {% for exporter in prometheus_exporters %}

      location /metrics/{{ exporter }} {
          allow {{ hostvars.monitor.nginx_public_addr }};
          deny all;

          proxy_set_header Host $host;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

          proxy_pass http://127.0.0.1:{{ prometheus_packages[exporter].port }}/metrics;
      }
      {% endfor %}
  - name: pknet-monitor.local
    # ssl_certbot_email: niels.martignene@protonmail.com
    config: |
      limit_req zone=default burst=100 nodelay;

      location /grafana {
          proxy_set_header Host $host;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

          proxy_pass http://127.0.0.1:9200;
      }

      location / {
          index index.html;

          rewrite ^(/?[a-zA-Z0-9]+)$ $1.html;
          rewrite ^(/?[a-zA-Z0-9]+)/$ $1 permanent;
          try_files $uri $uri/ =404;

          root /opt/static/live/goupile.fr;
      }
