# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see https://www.gnu.org/licenses/.

- name: Install packages
  package:
    update_cache: yes
    pkg:
      - ufw
    state: latest
  become: yes

- name: Configure IPv6
  template:
    src: ipv6.cfg.j2
    dest: /etc/network/interfaces.d/51-cloud-init-ipv6.cfg
    owner: root
    group: root
    mode: '0644'
  register: ipv6_config
  when: 'ovh_ipv6_addr is defined'
  become: yes

- name: Restart networking
  service:
    name: networking
    state: restarted
  when: ipv6_config.changed
  become: yes

- name: Configure ufw defaults
  ufw:
    direction: '{{ item.direction }}'
    policy: '{{ item.policy }}'
  loop:
    - direction: incoming
      policy: deny
    - direction: outgoing
      policy: allow
  notify:
    - restart ufw
  become: yes

- name: Configure ufw rules
  ufw:
    rule: '{{ item.rule }}'
    port: '{{ item.port }}'
    proto: '{{ item.proto }}'
  loop:
    - rule: limit
      port: 22
      proto: tcp
    - rule: allow
      port: 80
      proto: tcp
    - rule: allow
      port: 443
      proto: tcp
  become: yes

- name: Enable ufw
  ufw:
    state: enabled
  become: yes

- name: Reload ufw
  ufw:
    state: reloaded
  when: 'not ansible_check_mode'
  become: yes
